### ISSUE TITLE
Latest version not taking name parameter

### ISSUE THREAD

**Issue by bobvmierlo** [gcobb321/icloud3#118]
Just updated to 2.3.1 and noticed it doesn't take the name parameter from the ic3_config.yaml since this update.
It used to work fine with the last version I used, with which I also used the new 'devices:' parameters instead of the old 'track_devices:' divided by the > marks.

I already tried to completely remove all the icloud3 parts from HA and do a complete fresh install, but no luck there.

My ic3_config.yaml:
```
# --Track Devices Parameters-------------------------------
devices:
  - device_name: iphone_11_van_bob
    name: Bob
    picture: /local/bob.jpg
    iosapp_suffix: _3
```

The eventlog export (removed some lines for privacy reasons):
```
-- sys event --	20:59:36	-	-	-	-	-	Initializing iCloud3 v2.3.1 > Monday, Feb 08
-- sys event --	20:59:36	-	-	-	-	-	Event Log Version Check > Current release is being used. Version-2.3.0  (1/2/2021), /config/www/custom_cards
-- sys event --	20:59:36	-	-	-	-	-	Stage 1 > Prepare iCloud3 for myemail@address.com
-- sys event --	20:59:36	-	-	-	-	-	iCloud3 Directory > /config/custom_components/icloud3
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > devices: [{`device_name`: `iphone_11_van_bob`, `name`: `Bob`, `picture`: `/local/bob.jpg`, `iosapp_suffix`: `_3`}, {`device_name`: `iphone_van_linde`, `name`: `Annelinde`, `noiosapp`: True}]
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > inzone_interval: 60 min
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > stationary_inzone_interval: 20 min
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > stationary_zone_offset: 0,1
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > display_zone_fname: True
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > unit_of_measurement: km
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > time_format: 24
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > old_location_threshold: 2 min
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > distance_method: waze
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > waze_region: EU
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > waze_realtime: True
-- sys event --	20:59:36	-	-	-	-	-	config_ic3 Parameter > log_level: debug
-- sys event --	20:59:36	-	-	-	-	-	iCloud3 Configuration File > /config/config_ic3.yaml
-- sys event --	20:59:36	-	-	-	-	-	Set Up Waze > Region-EU, MinDist-1 km, MaxDist-1000 km, Realtime-False
-- sys event --	20:59:36	-	-	-	-	-	Stage 2 > Set up tracked device parameters
-- sys event --	20:59:36	-	-	-	-	-	Decoding ... Config Devices Parameter >, ✓ iphone_11_van_bob > Name-11Vanbob, Picture-/local/bob.jpg, iOSAppSuffix-_3, Type-iPhone
```
![image](https://user-images.githubusercontent.com/38190383/107275000-7e5f4480-6a51-11eb-98f8-9aaf50814a1f.png)

**Comment by gcobb321** [comment]
iCloud3 v2.3.2 was just updated to fix this problem. Download the new version from HACS.

------
The following bug was fixed in the iCloud3 v2.3.2 update:
- The Name parameter was not being decoded correctly due to a bug introduced in iCloud3 v2.3.1.

Also:
- Added a device_type parameter to override a value extracted from the device_name parameter.
- Updated the iCloud3 version number which was not updated in the v2.3.1 release.

**Comment by bobvmierlo** [comment]
Unfortunately 2.3.2 causes an error preventing my to restart HA Core

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1471, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 415, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 202, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/icloud3/device_tracker.py", line 25
    VERSION = '2.3.2"
                    ^
SyntaxError: EOL while scanning string literal
```

**Comment by gcobb321** [comment]
Bad quote mark. Just uploaded a fix. Try again.
