### ISSUE TITLE
Error when upgrading from 2.3.1 to 2.3.2

### ISSUE THREAD

**Issue by jaywryan** [gcobb321/icloud3#121]
I am unable to upgrade.  I can roll back, just fine.  I am using HACS and I am running in a container.

2021-02-12 21:50:13 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration device_tracker - received exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 835, in async_forward_entry_setup
result = await async_setup_component(self.hass, domain, self._hass_config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 57, in async_setup_component
return await setup_tasks[domain] # type: ignore
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 835, in async_forward_entry_setup
result = await async_setup_component(self.hass, domain, self._hass_config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 57, in async_setup_component
return await setup_tasks[domain] # type: ignore
File "/usr/src/homeassistant/homeassistant/setup.py", line 64, in async_setup_component
return await task # type: ignore
File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
processed_config = await conf_util.async_process_component_config(
File "/usr/src/homeassistant/homeassistant/config.py", line 826, in async_process_component_config
platform = p_integration.get_platform(domain)
File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 779, in exec_module
File "<frozen importlib._bootstrap_external>", line 916, in get_code
File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/config/custom_components/icloud3/device_tracker.py", line 25
VERSION = '2.3.2"
^
SyntaxError: EOL while scanning string literal

**Comment by gcobb321** [comment]
That coding error was fixed a few days ago.  Some have had had success reinstalling through HACS but others have found HACS was still installing the same version. 

The easiest fix is to edit *device_tracker.py* in the *icloud3* directory. Change the double quote on line 25 to a single quote so it reads `VERSION=‘2.3.2’`

**Comment by jaywryan** [comment]
Thanks, that worked!
