### ISSUE TITLE
Confirmation of Apple ID Verification Code failed - v2.4.0

### ISSUE THREAD

**Issue by rodpayne** [gcobb321/icloud3#145]
I don't know if this could help track down this problem, but for what it's worth, here is some info.  The error was consistent.  Every time Confirm was clicked, the "Failed to call service configurator/configure. 'Icloud3' object has no attribute '_icloud_2fa1_show_trusted_device_request_form'" error popped up.  It worked after restarting HA.

![icloud3 request verification code](https://user-images.githubusercontent.com/28266684/115039552-cb1a2e00-9e8d-11eb-9ab9-b1684541e787.png)
![icloud3 no attribute](https://user-images.githubusercontent.com/28266684/115039476-b76ec780-9e8d-11eb-8b3f-a3c4d1635a3c.png)

```
2021-04-16 07:58:02 ERROR (SyncWorker_53) [custom_components.icloud3.pyicloud_ic3] (Status Code 403)
2021-04-16 07:58:02 ERROR (SyncWorker_53) [custom_components.icloud3.device_tracker] Failed to verify account > Error- (Status Code 403)
2021-04-16 07:58:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2765627528] 'Icloud3' object has no attribute '_icloud_2fa1_show_trusted_device_request_form'
Traceback (most recent call last):
File "/config/custom_components/icloud3/device_tracker.py", line 9577, in _icloud_2fa2_handle_verification_code_entry
valid_code = self.api.validate_2fa_code(self.verification_code)
File "/config/custom_components/icloud3/pyicloud_ic3.py", line 608, in validate_2fa_code
self.session.post(
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/config/custom_components/icloud3/pyicloud_ic3.py", line 175, in request
self._raise_error(response.status_code, response.reason)
File "/config/custom_components/icloud3/pyicloud_ic3.py", line 235, in _raise_error
raise api_error
custom_components.icloud3.pyicloud_ic3.PyiCloudAPIResponseException: (Status Code 403)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 233, in async_handle_service_call
await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/icloud3/device_tracker.py", line 9592, in _icloud_2fa2_handle_verification_code_entry
self._icloud_2fa1_show_trusted_device_request_form()
AttributeError: 'Icloud3' object has no attribute '_icloud_2fa1_show_trusted_device_request_form'
```

**Comment by gcobb321** [comment]
Fixed in iCloud3 v2.4.1 just uploaded to HACS and the iCloud3 GitHub repository.
