### ISSUE TITLE
Error 'locations'

### ISSUE THREAD

**Issue by barto95100** [gcobb321/icloud3#150]
Hi,

I have more log : 

2021-04-27 23:40:03 ERROR (SyncWorker_36) [custom_components.icloud3.device_tracker] 'locations'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 3112, in _refresh_pyicloud_devices_location_data
    for location in devices_data['locations']:
KeyError: 'locations'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 3112, in _refresh_pyicloud_devices_location_data
    for location in devices_data['locations']:
KeyError: 'locations'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 3112, in _refresh_pyicloud_devices_location_data
    for location in devices_data['locations']:
KeyError: 'locations'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 3112, in _refresh_pyicloud_devices_location_data
    for location in devices_data['locations']:
KeyError: 'locations'

do you have idea of the probblem ? and how to fix ?

**Comment by gcobb321** [comment]
device_data[‘locations’] contains the location information returned from iCloud. When no data is returned, that error can indicate a communication error with iCloud servers or a an authentication issue. You can see from the error message with the line 3112 tag that iCloud3 is trying to do a refresh. A lot of times restarting iCloud3 (Event Log > Actions> Restart iCloud3) will refresh the communication see session and clear up the error. 

I’ll look at displaying a friendly message.
