### ISSUE TITLE
Keyerror: ’interval’

### ISSUE THREAD

**Issue by zyjex** [gcobb321/icloud3#18]
i've tried your plugin for a few days now, but i gotten this error 2 days in a row, it seems like it happens when i leave home or when i arrive home. It crashes home assistant and makes it unresponsive.

2019-01-31 15:28:31 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/device_tracker/icloud3.py", line 845, in _device_polling_15_sec_timer_loop
self._update_tracked_devices()
File "/config/custom_components/device_tracker/icloud3.py", line 1040, in _update_tracked_devices
attrs[CONF_INTERVAL],
KeyError: 'interval'

and then home assistant cant be reached, and its just sits like this forever

2019-01-31 15:33:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.farstu_ute_311 is taking over 10 seconds
2019-01-31 15:33:41 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.processor_use is taking over 10 seconds
2019-01-31 15:33:41 WARNING (MainThread) [homeassistant.helpers.entity] Update of lock.idlock_575 is taking over 10 seconds
2019-01-31 15:33:41 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ackumulatortank_382 is taking over 10 seconds
2019-01-31 15:33:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.kameraping is taking over 10 seconds
2019-01-31 15:33:51 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.josefs_iphone_battery_state_2 is taking over 10 seconds

I had to disable icloud3 and the crashes stoppes

**Comment by gcobb321** [comment]
I've fixed this and a few other things and am doing some final testing now. I hope to have the update on github by Monday.

**Comment by gcobb321** [comment]
It is fixed in the next release. Final testing now.
