### ISSUE TITLE
Can't get the Persistent Message to show for 2FA Verification

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3#218]
It's been ~2 months so I'm due to reauthenticate my Apple ID with iCloud3. It has previously been working well for months. I can't seem to get the Apple 2FA Allow window to show at the same time as the persistent notification to fire to enter the code into iCloud3. 

When I select reset iCloud Interface it triggers the Apple 2FA window to popup but I don't have anywhere to enter it.

How can I get the notification to appear to enter the 2FA code?

```
2022-05-19 21:23:17 ERROR (SyncWorker_40) [custom_components.icloud3.device_tracker] Authentication needed for Account (Status Code 421)
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6779, in _setup_tracked_devices_for_fmf
    self._log_rawdata("iCloud FmF Raw Data - (api_friends.data)", api_friends.data)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1079, in data
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1006, in refresh_client
    req = self.session.post(self._friend_endpoint, data=mock_payload, params=params)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 177, in request
    return self.request(method, url, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 179, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 239, in _raise_error
    raise api_error
custom_components.icloud3.pyicloud_ic3.PyiCloudAPIResponseException: Authentication needed for Account (Status Code 421)
```
![2022-05-19_21-12-13 029](https://user-images.githubusercontent.com/6526076/169430437-a0d922d6-16f8-4d7d-b203-014ce715fbfb.png)

**Comment by gcobb321** [comment]
Click Notifications on HA Sidebar. There should be an orange dot. Then follow directions to open the code entry window. See iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1.2-getting-started?id=_2-factor-authentication-icloud3-v23-and-later)

**Comment by sinoon** [comment]
@Snuffy2 Hi buddy, how do you fix this problem?

**Comment by gcobb321** [comment]
The error indicates that an Authentication is required. You will have to go through the Authentication and verification code process above.
