### ISSUE TITLE
[ERROR] local variable 'v2_trigger_changed_secs' referenced before assignment

### ISSUE THREAD

**Issue by harryd100** [gcobb321/icloud3#29]
Since update to v2.1 every 5 sec i receive:

  File "/config/custom_components/icloud3/device_tracker.py", line 1420, in _polling_loop_5_sec_device
    self._secs_to_time(v2_trigger_changed_secs))
UnboundLocalError: local variable 'v2_trigger_changed_secs' referenced before assignment
2020-03-22 16:43:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Device Update Error, Error=<class 'ValueError'>
2020-03-22 16:43:05 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] local variable 'v2_trigger_changed_secs' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1420, in _polling_loop_5_sec_device
    self._secs_to_time(v2_trigger_changed_secs))
UnboundLocalError: local variable 'v2_trigger_changed_secs' referenced before assignment
2020-03-22 16:43:05 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Device Update Error, Error=<class 'ValueError'>
2020-03-22 16:43:10 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] local variable 'v2_trigger_changed_secs' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1420, in _polling_loop_5_sec_device
    self._secs_to_time(v2_trigger_changed_secs))
UnboundLocalError: local variable 'v2_trigger_changed_secs' referenced before assignment
2020-03-22 16:43:10 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] Device Update Error, Error=<class 'ValueError'>
2020-03-22 16:43:15 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] local variable 'v2_trigger_changed_secs' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1420, in _polling_loop_5_sec_device
    self._secs_to_time(v2_trigger_changed_secs))
UnboundLocalError: local variable 'v2_trigger_changed_secs' referenced before assignment
2020-03-22 16:43:15 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] Device Update Error, Error=<class 'ValueError'>

Any idea where to look?

Regards, Harry

**Comment by gcobb321** [comment]
The v2_trigger_changed_secs variable is set if you are running the iOS App v2 and not set with v1. The error you are seeing is in a message when a trigger change is detected.

What version of the iOS App are you running?
Have you installed the v2 app and mobile_app integration?
Does the Event Log show anything about the iOS app when iCloud3 starts? 

Go to the Event Log and scroll down until you see the various Initializing Stage x messages to see info about the iOS app. 

I can put a check for the version number in the code and post an update in the `development` directory of the GitHub repository to see if it catches the error for you to try.

**Comment by gcobb321** [comment]
I've uploaded a version of icloud3 that takes care of this issue to the development directory in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.1.0x).

Download it and see if it solves your problem. Let me know if it is now working or there are further issues.

**Comment by gcobb321** [comment]
Reopen this issue if the problem still exists

**Comment by gcobb321** [comment]
Release Candidate 4 is now available. See the Release Candidate Change Log file for information on the changes. Download it [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.2.0-rc4)
