### ISSUE TITLE
iCloud3 v3 - Release Candidate 9 uploaded (12/20/2023)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#297]
**Description** - This release includes some bug fixes and new features.

**Change Log** - Visit the Release Page [here](https://github.com/gcobb321/icloud3/releases) for a complete list of the changes.

### Update using HACS
When I create a new release, it is not picked up by HACS immediately. It might take HACS up to 48-hours to pick up the new release information and add it to the Devices & Services screen.

Check to see if the new version of iCloud3 is displayed as an available update on the Devices & Services screen. If it is not displayed there, do the following:
1. Open HACS from it's sidebar icon. Select Integrations, then type iCloud3 in the search field and press Enter.
2. Two items are displayed - iCloud3 Device Tracker and iCloud3 v3, Development Version.
3. Select iCloud3 v3, Development Version, click the 3-dots in the upper-right corner to open the menu. 
4. Select Update Information, Then select Download or Redownload. HACS will download and install the new version.
5. Restart HA like you normally do.

**Comment by garethcook** [comment]
Just updated from the previous release, now borked. I get an alert in the UI:
`Invalid config
The following integrations and platforms could not be set up:

[icloud3](https://gcobb321.github.io/icloud3_v3_docs/#/) ([Show logs](http://homeassistant.local:8123/config/logs?filter=icloud3))
Please check your config and [logs](http://homeassistant.local:8123/config/logs).`

**and in the logs**

`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 21:44:30 (1 occurrences)
Last logged: 21:44:30

Setup failed for custom integration 'icloud3': Unable to import component: No module named 'custom_components.icloud3.const_more_info'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/icloud3/__init__.py", line 31, in <module>
    from .helpers.messaging             import (_trace, _traceha, open_ic3_log_file,
  File "/config/custom_components/icloud3/helpers/messaging.py", line 26, in <module>
    from ..const_more_info  import more_info_text
ModuleNotFoundError: No module named 'custom_components.icloud3.const_more_info'`

**Comment by gcobb321** [comment]
Somehow. a file (const_more_info.py) was missing from the zip and GitHub iCloud3 directory. I've rebuilt the release and you should be OK now.

Get it again.
