### ISSUE TITLE
Error - Status Code 501

### ISSUE THREAD

**Issue by Animizio** [gcobb321/icloud3#308]
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:6779
Integration: icloud3 (documentation, issues)
First occurred: 15:39:30 (1 occurrences)
Last logged: 15:39:30

(Status Code 501)
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6779, in _setup_tracked_devices_for_fmf
    self._log_rawdata("iCloud FmF Raw Data - (api_friends.data)", api_friends.data)
                                                                  ^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1079, in data
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1006, in refresh_client
    req = self.session.post(self._friend_endpoint, data=mock_payload, params=params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 179, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 239, in _raise_error
    raise api_error
custom_components.icloud3.pyicloud_ic3.PyiCloudAPIResponseException:  (Status Code 501)
`

**Comment by gcobb321** [comment]
The Find-my-Friends tracking method was discontinued by App in May, 2023. That generated the 501 Connection error

**Comment by Likowaas** [comment]
Hey, is there anything new?

**Comment by gcobb321** [comment]
Find my friends is dead forever. Apple does not provide a web interface to get the needed info. I’m working on supporting multiple Apple accounts right now
