### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by dony71** [gcobb321/icloud3#329]
when adding icloud3 integration, get error 
Config flow could not be loaded: {"message":"Invalid handler specified"}
Home Assistant 2023.6.0
iCloud3 v3 v3.0.2a

log shows

> 

2024-04-10 18:22:46.545 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.icloud3.device_tracker
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/__init__.py", line 36, in <module>
    from .support.v2v3_config_migration import iCloud3_v2v3ConfigMigration
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/v2v3_config_migration.py", line 112, in <module>
    from .                      import config_file
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/config_file.py", line 37, in <module>
    from ..support              import start_ic3
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/start_ic3.py", line 64, in <module>
    from ..support              import mobapp_data_handler
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/mobapp_data_handler.py", line 23, in <module>
    from ..support              import zone_handler
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/zone_handler.py", line 472, in <module>
    def ha_added_zone_entity_id(event: EventType[event.EventStateChangedData]) -> None:
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.event' has no attribute 'EventStateChangedData'
2024-04-10 18:22:46.605 ERROR (MainThread) [homeassistant.config] Platform error: device_tracker
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/__init__.py", line 36, in <module>
    from .support.v2v3_config_migration import iCloud3_v2v3ConfigMigration
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/v2v3_config_migration.py", line 112, in <module>
    from .                      import config_file
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/config_file.py", line 37, in <module>
    from ..support              import start_ic3
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/start_ic3.py", line 64, in <module>
    from ..support              import mobapp_data_handler
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/mobapp_data_handler.py", line 23, in <module>
    from ..support              import zone_handler
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/zone_handler.py", line 472, in <module>
    def ha_added_zone_entity_id(event: EventType[event.EventStateChangedData]) -> None:
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.event' has no attribute 'EventStateChangedData'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 842, in get_platform
    raise ImportError(
ImportError: Exception importing custom_components.icloud3.device_tracker

>

**Comment by gcobb321** [comment]
The error is probably caused by iCloud3 looking at the time a zone was added to HA. 

You are running HA 2023.6.0 which is over 9-months old. iCloud3 is probably looking at a field added to HA in one of its updates. You will probably  need to update HA to the current release. 

Edit: I updated the required HA version to 2024.2.1 in the iCloud3 repository to correct this.

**Comment by dony71** [comment]
> The error is probably caused by iCloud3 looking at the time a zone was added to HA.
> 
> You are running HA 2023.6.0 which is over 9-months old. iCloud3 is probably looking at a field added to HA in one of its updates. You will probably need to update HA to the current release.
> 
> Edit: I updated the required HA version to 2024.2.1 in the iCloud3 repository to correct this.

Unfortunately I cannot upgrade HA to 2024.2.1 since I have old board which not support it :(

**Comment by gcobb321** [comment]
I've fixed this in v3.0.4 that has not been released yet. Here is an early copy that will have at least one more change before it is released.

Unzip it into the iCloud3 directory and restart HA.
[icloud3 v3.0.4.zip](https://github.com/gcobb321/icloud3/files/15226850/icloud3.v3.0.4.zip)
