### ISSUE TITLE
invalid request error

### ISSUE THREAD

**Issue by errolsancaktar** [gcobb321/icloud3#33]
Uninstalled and error went away
When running i get this error:

`sqlalchemy.exc.InvalidRequestError:` This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined> (Background on this error at: http://sqlalche.me/e/7s2a)
2020-04-15 18:30:07 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined> (Background on this error at: http://sqlalche.me/e/7s2a)
2020-04-15 18:30:07 ERROR (Recorder) [homeassistant.components.recorder] Error saving events: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined> (Background on this error at: http://sqlalche.me/e/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 410, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 452, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
    code="7s2a",
`

**Comment by gcobb321** [comment]
The messages added to the HA log file uses UTF-8 encoding. Make sure 
your sql data base is set up to use UTF-8 rather than Ascii encoding.

------ Original Message ------
