### ISSUE TITLE
Internal error retrying icloud location data error

### ISSUE THREAD

**Issue by riemers** [gcobb321/icloud3#34]
I am getting these messages..

```2019-04-28 20:49:00 ERROR (SyncWorker_29) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-04-28 20:49:00 ERROR (SyncWorker_29) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud/OverallUpdate-tuple index out of range)
2019-04-28 20:49:00 ERROR (SyncWorker_29) [custom_components.icloud3.device_tracker] tuple index out of range
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1671, in _update_device_icloud
    loc_attr_timestamp  = dev_data[11]
IndexError: tuple index out of range
2019-04-28 20:49:01 ERROR (SyncWorker_29) [custom_components.icloud3.device_tracker] 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 3117, in _trace_device_attributes
    trace_attrs_in_attrs = {k: v for k, v in attrs_in_attrs.items() \
AttributeError: 'NoneType' object has no attribute 'items'
2019-04-28 20:49:01 ERROR (SyncWorker_29) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 3105, in _trace_device_attributes
    if ATTR_LOCATION in attrs:
TypeError: argument of type 'NoneType' is not iterable
2019-04-28 20:49:01 ERROR (SyncWorker_29) [custom_components.icloud3.device_tracker] local variable 'loc_attr_timestamp' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1986, in _prepare_data_icloud
    location_isold_flag, loc_attr_timestamp, altitude,
UnboundLocalError: local variable 'loc_attr_timestamp' referenced before assignment
```

**Comment by riemers** [comment]
And after a restart it was gone again. Feel free to close the issue if you think it has no value any further.

**Comment by gcobb321** [comment]
What version are you running? It is listed in the device_tracker attributes.  The latest is 1.0.3.
