### ISSUE TITLE
Version 2.1 calls to refresh and restart the service will report an error, and the automatic refresh time will also report an error, which will not be updated after a long time

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#36]
2020-05-16 23:13:46 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 4526, in _trace_device_attributes
    if ATTR_LOCATION in attrs:
TypeError: argument of type 'NoneType' is not iterable
2020-05-16 23:13:46 WARNING (MainThread) [homeassistant.components.sensor] Updating baidu_face sensor took longer than the scheduled update interval 0:00:02
2020-05-16 23:13:46 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] local variable 'loc_time_secs' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2907, in _get_famshr_data
    location_isold_flag, loc_time_secs, altitude,
UnboundLocalError: local variable 'loc_time_secs' referenced before assignment

---------------------------------------------------------------------------------------------------------

2020-05-16 12:21:30 ERROR (SyncWorker_9) [custom_components.icloud3.pyicloud_ic3]  (450)
2020-05-16 12:21:30 ERROR (SyncWorker_9) [custom_components.icloud3.pyicloud_ic3.http] name '_LOGGER' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 176, in _raise_error
    self.session.cookies.clear()
AttributeError: 'PyiCloudSession' object has no attribute 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 111, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 182, in _raise_error
    _LOGGER.exception(err)
NameError: name '_LOGGER' is not defined

**Comment by a120578270** [comment]
device_tracker: 
 - platform: icloud3
    username: !secret myname_iphoneuser
    password: !secret myname_iphonepass
    group: family
    tracking_method: famshr
    track_devices:
        - myiPhone
    inzone_interval: 25 min     
    stationary_inzone_interval: 15 min

**Comment by gcobb321** [comment]
From the first error message, (if attr-location in attrs), indicates no location information was returned from the iCloud web services. The (450) error later on is issued when the iCloud account needs to be Reauthenticated. You didn’t indicate the iCloud3 version you are using but I am putting the final touches on v2.2.0 which solves all the notification problems with the FamShr method and adds some new features. I need to do some change docs and will post a release candidate in the ‘development-v2.2.0’ directory tomorrow or the next day. I’ll post a a comment here when it’s available.
