### ISSUE TITLE
Error on HACS update check

### ISSUE THREAD

**Issue by japyjaap** [gcobb321/icloud3#362]
Hi,

I'm having some issues with random restarting of my HA, so I've enabled some additional debugging and dived in the logs. I found an error with iCloud3. I don't think this is the cause of instability, but it does seem like bug.

`2024-07-24 07:00:00.189 ERROR (SyncWorker_16) [custom_components.icloud3] Non-thread-safe operation invoked on an event loop other than the current one
Traceback (most recent call last):
File "/config/custom_components/icloud3/icloud3_main.py", line 245, in _polling_loop_5_sec_device
self._main_5sec_loop_special_time_control()
File "/config/custom_components/icloud3/icloud3_main.py", line 601, in _main_5sec_loop_special_time_control
self._timer_tasks_every_hour()
File "/config/custom_components/icloud3/icloud3_main.py", line 1310, in _timer_tasks_every_hour
Gb.hass.loop.create_task(hacs_ic3.check_hacs_icloud3_update_available())
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 458, in create_task
task = tasks.Task(coro, loop=self, name=name, context=context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 797, in call_soon
self._check_thread()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 834, in _check_thread
raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
2024-07-24 07:00:00.190 ERROR (SyncWorker_16) [homeassistant] Error doing job: Task was destroyed but it is pending! (<Task pending name='Task-8039' coro=<check_hacs_icloud3_update_available() running at /config/custom_components/icloud3/support/hacs_ic3.py:28> created at /usr/local/lib/python3.12/asyncio/base_events.py:458>): File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap`

**Comment by gcobb321** [comment]
This may have been fixed in v3.0.5.6. I can not create it and reopen this issue if you are still having an issue.
