### ISSUE TITLE
Sign in issues, since update to 2024.7.4 core

### ISSUE THREAD

**Issue by andyblac** [gcobb321/icloud3#364]
Is anyone else having sign in issues since updating the HA Core ?, all I get now is:

```
This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/helpers/messaging.py:467
integration: iCloud3 v3 (documentation, issues)
First occurred: 12:28:13 (2 occurrences)
Last logged: 12:28:13

iCloud3 Error > An error occurred logging into the iCloud Account. iCloud Authentication Failed > Username or Password is not valid, Error-421)
```

**Comment by gcobb321** [comment]
I just updated HA to 2024.7.4 on an Rpi4 and Rpi5 and iCloud3 started without any problems. Have you gone into the Configure Settings > iCloud Account & Mobile App screen and reviewed the username/password fields?. 

I did notice that the HA guys changed how the zone is displayed in the device_tracker entity. Before if the state value was 'home', it would be displayed as 'Home'. Now it is displayed as 'home'.

**Comment by andyblac** [comment]
> I just updated HA to 2024.7.4 on an Rpi4 and Rpi5 and iCloud3 started without any problems. Have you gone into the Configure Settings > iCloud Account & Mobile App screen and reviewed the username/password fields?.
> 
> I did notice that the HA guys changed how the zone is displayed in the device_tracker entity. Before if the state value was 'home', it would be displayed as 'Home'. Now it is displayed as 'home'.

it was working fine before I updated HA and the to the latest iCloudv3 version

edit:

just checked user and pass both are correct. I can sing in to iCloud.com with the same email and password without issue.

**Comment by gcobb321** [comment]
Adding a device no linger works either after the 2024.7.4 update

**Comment by andyblac** [comment]
> Adding a device no linger works either after the 2024.7.4 update

nor editing one, it causes all the entities to be disconnected and creates new ones with `_2` at the end.

**Comment by andyblac** [comment]
> I just updated HA to 2024.7.4 on an Rpi4 and Rpi5 and iCloud3 started without any problems. Have you gone into the Configure Settings > iCloud Account & Mobile App screen and reviewed the username/password fields?.

have you tried singing out and back in, I had to remove the integration and reinstall it, due to editing device bug (all old entities are discconected and new ones with `_2` created, and as the old entities do not have a UUID you can not delete them, so hence the reason I had to uninstall and reinstall.) That when I started to get the sign in issues.

**Comment by gimmel** [comment]
Yesterday, after the update to 2024.7.4, I suddenly could only see my own iCloud data, but not the iPhone data of the family.
Today I used "ha core update --version 2024.7.3" to go back to the last version and suddenly I can see all iCloud stuff again.
2024.7.4 is definitely a problem for iCloud3 3.0.5.5.

**Comment by andyblac** [comment]
just tried to revert to HA 2024.7.3 same result sign-in failure

I enabled debug here what it shows

```
2024-07-31 11:49:21.129 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0536] CONFIG ❗Initialize PyiCloud Service, establish iCloud Location Services connection
2024-07-31 11:49:21.132 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0927] CONFIG ❗Read Cookies from /config/.storage/iCloud/an......icloudcom
2024-07-31 11:49:21.135 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0494] CONFIG ❗AUTHENTICATING iCloud Account Access,  (an......@ic........), config
2024-07-31 11:49:21.138 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0618] CONFIG ❗Authenticating account  (an......@ic........) with token
2024-07-31 11:49:22.060 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0733] CONFIG ❗Authenticate.authenticate_with_password > Successful
2024-07-31 11:49:22.388 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0689] CONFIG ❗PyiCloudAPIResponseException.authenticate_with_token > Token is not valid, error-Missing apple_id field, 2fa Needed-False
2024-07-31 11:49:22.394 DEBUG (SyncWorker_8) [custom_components.icloud3] [pyicloud_ic3:0642] CONFIG ❗iCloud Authentication Failed > Username or Password is not valid, Error-400
2024-07-31 11:49:22.395 ERROR (MainThread) [icloud3-cf] Error logging into iCloud service: iCloud Authentication Failed > Username or Password is not valid, Error-400
```

**Comment by andyblac** [comment]
@gcobb321 what does this mean

`❗PyiCloudAPIResponseException.authenticate_with_token > Token is not valid, error-Missing apple_id field, 2fa Needed-False`

**Comment by andyblac** [comment]
just restored backup to HA 2024.7.3 (known working backup), one this now fails to sign in.

got this on 1st try to sign-in
```
2024-07-31 12:36:18.338 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/.storage/icloud3/configuration',) inside the event loop by custom integration 'icloud3' at custom_components/icloud3/helpers/common.py, line 307: data = json_util.load_json(filename) (offender: /usr/src/homeassistant/homeassistant/util/json.py, line 78: with open(filename, mode="rb") as fdesc:), please create a bug report at https://github.com/gcobb321/icloud3_v3/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1267, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1297, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 573, in async_step_user
    config_file.load_storage_icloud3_configuration_file()
  File "/config/custom_components/icloud3/support/config_file.py", line 68, in load_storage_icloud3_configuration_file
    success = read_storage_icloud3_configuration_file()
  File "/config/custom_components/icloud3/support/config_file.py", line 124, in read_storage_icloud3_configuration_file
    Gb.conf_file_data = load_json_file(filename)
  File "/config/custom_components/icloud3/helpers/common.py", line 307, in load_json_file
    data = json_util.load_json(filename)

2024-07-31 12:36:23.459 ERROR (SyncWorker_11) [custom_components.icloud3] iCloud3 Error > An error occurred logging into the iCloud Account. iCloud Authentication Failed > Username or Password is not valid, Error-421)
2024-07-31 12:36:23.463 ERROR (SyncWorker_11) [custom_components.icloud3] 'NoneType' object has no attribute 'init_step_complete'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3_control.py", line 218, in stage_4_setup_data_sources
    start_ic3.setup_data_source_ICLOUD()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1350, in setup_data_source_ICLOUD
    if pyicloud_ic3_interface.verify_pyicloud_setup_status() is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/support/pyicloud_ic3_interface.py", line 120, in verify_pyicloud_setup_status
    if 'Authenticate' not in Gb.PyiCloud.init_step_complete:
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'init_step_complete'
```

**Comment by andyblac** [comment]
OK, got it back working reverted to HA 2024.7.3, removed integration, signed in to appleid on website, and it was LOCKED probably due to  all the failed attempts, unlocked it and now back working. I'll stay on HA 2024.7.3 for now.

**Comment by gimmel** [comment]
Oh, the iCloud lock is another problem. My account was locked a few days ago (while I was trying to use iCloud in a VM to send AirTag positions to HomeAssistant).
I now believe these are coincidences because I had to agree to changed iCloud data shortly afterwards. I suspect the blocks are due to problems at Apple. When unlocking the account, I also got several messages like "Server not available. Try again later."

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.7 appears to be working under HA 2024.7.4/HAOS 12.4

The zip file below contains an update to iCloud3 v3. I have not released it yet but would like you to try it to make sure there are no other issues I need to look at. Let me know if it now works. TThanks.

Gary

Unzip icloud3 v3.0.5.7 into the _config/custom_components/icloud3_ directory and restart HA.

[icloud3 v3.0.5.7.zip](https://github.com/user-attachments/files/16442898/icloud3.v3.0.5.7.zip)

**Comment by andyblac** [comment]
> iCloud3 v3.0.5.7 appears to be working under HA 2024.7.4/HAOS 12.4
> 
> The zip file below contains an update to iCloud3 v3. I have not released it yet but would like you to try it to make sure there are no other issues I need to look at. Let me know if it now works. TThanks.
> 
> Gary
> 
> Unzip icloud3 v3.0.5.7 into the _config/custom_components/icloud3_ directory and restart HA.
> 
> [icloud3 v3.0.5.7.zip](https://github.com/user-attachments/files/16442898/icloud3.v3.0.5.7.zip)

I'll take a look in the morning UK time, I'll let you know

**Comment by gimmel** [comment]
Thanks for your work. At first glance, version 3.0.5.7 no longer seems to cause any problems with HA 2024.7.4.

What has changed in 2024.7.4, or in other words: what did you have to change to make it work again?

**Comment by gcobb321** [comment]
There were some issues in the Configure Update Device screen where famshr device tables were not filled in. Before, the program would fill them in and go to the next one. I’ve also been working on I/O routines for the next release and that may have fixed some issues. 

Glad it’s working

**Comment by andyblac** [comment]
yup, 3.0.5.7 seems to fix the issue. this can be close for my side.

**Comment by gimmel** [comment]
There were no errors anymore since I updated to 3.0.5.7 (and then back to HA 2024.7.4), but now I saw that all the values were frozen since the update. Now I downgraded to 2024.7.3 and suddenly I get fresh, actual values.

**Comment by AlexMC** [comment]
Have the same issue and 3.0.5.7 doesnt seem to fix it, login details are correct, my icloud account is ok, not locked, but icloud3 doesn't seem to be able to login.

**Comment by andyblac** [comment]
> Have the same issue and 3.0.5.7 doesnt seem to fix it, login details are correct, my icloud account is ok, not locked, but icloud3 doesn't seem to be able to login.

1st double check account is not locked, by singing in to http://appleid.apple.com, then try removing the integration, restart HA, reinstall and allow it restore the configuration. then do a full reboot.

**Comment by gcobb321** [comment]
Closing due to no activity and the release of v3.1.5
