### ISSUE TITLE
Version 2.2 calls icloud3_restart and then reports an error

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#37]
2020-05-26 14:29:22 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] Unable to find service zone/reload
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 977, in _start_icloud3
    self._initialize_zone_tables()
  File "/config/custom_components/icloud3/device_tracker.py", line 5358, in _initialize_zone_tables
    self.hass.services.call(ATTR_ZONE, "reload")
  File "/usr/src/homeassistant/homeassistant/core.py", line 1174, in call
    self._hass.loop,
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 1211, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service zone/reload
2020-05-26 14:29:25 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] local variable 'icon_name' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 5263, in _initialize_device_zone_fields
    self.stat_zone_devicename_icon[devicename] = icon_name
UnboundLocalError: local variable 'icon_name' referenced before assignment

2020-05-26 14:29:26 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] local variable 'icon_name' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 5263, in _initialize_device_zone_fields
    self.stat_zone_devicename_icon[devicename] = icon_name
UnboundLocalError: local variable 'icon_name' referenced before assignment
2020-05-26 14:29:27 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] local variable 'icon_name' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 5263, in _initialize_device_zone_fields
    self.stat_zone_devicename_icon[devicename] = icon_name
UnboundLocalError: local variable 'icon_name' referenced before assignment
2020-05-26 14:29:28 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] local variable 'icon_name' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 5263, in _initialize_device_zone_fields
    self.stat_zone_devicename_icon[devicename] = icon_name
UnboundLocalError: local variable 'icon_name' referenced before assignment
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_6) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:35 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1465, in _polling_loop_5_sec_device
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:35 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] Device Update Error, Error-<class 'ValueError'>
2020-05-26 14:29:40 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1465, in _polling_loop_5_sec_device
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:40 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] Device Update Error, Error-<class 'ValueError'>
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1465, in _polling_loop_5_sec_device
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] Device Update Error, Error-<class 'ValueError'>
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:29:50 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1465, in _polling_loop_5_sec_device
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:50 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] Device Update Error, Error-<class 'ValueError'>
2020-05-26 14:29:55 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1465, in _polling_loop_5_sec_device
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:29:55 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] Device Update Error, Error-<class 'ValueError'>

2020-05-26 14:30:00 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1465, in _polling_loop_5_sec_device
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:30:00 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] Device Update Error, Error-<class 'ValueError'>
2020-05-26 14:30:00 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:30:00 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:30:00 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:30:00 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:30:01 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:30:01 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')
2020-05-26 14:30:01 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2170, in _update_device_icloud
    self._check_outside_zone_no_exit(devicename, zone, latitude, longitude)
  File "/config/custom_components/icloud3/device_tracker.py", line 6293, in _check_outside_zone_no_exit
    zone_radius_accuracy_m = zone_radius_m + self.gps_accuracy_threshold
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2020-05-26 14:30:01 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-unsupported operand type(s) for +: 'NoneType' and 'int')

**Comment by a120578270** [comment]
device_tracker:

platform: icloud3
username: !secret myname_iphoneuser
password: !secret myname_iphonepass
group: family
tracking_method: famshr
track_devices:
- myiPhone
inzone_interval: 25 min
stationary_inzone_interval: 15 min

**Comment by gcobb321** [comment]
What version of HA are you running?
Go to sidebar>Developer Tools>Services. Click the down arrow by services and the list of services opens. Scroll to the bottom.  My list shows zone.reload. Do you see zone.reload on your system?

Do you see any errors if you just restart HA ... ?

I will add additional error checking tomorrow and post an update.

**Comment by a120578270** [comment]
The HA version is 0.102.2. After calling the restart service and reporting an error, all contents in the icloud3 attribute could not be obtained, and only HA was restarted.


![image](https://user-images.githubusercontent.com/58241282/82879660-d4e22c80-9f6f-11ea-9688-0eb2b22ac352.png)

**Comment by gcobb321** [comment]
The zone.reload service was added to HA around v0.105 I think so trapping the error and continuing with the zone initialization will fix that issue. All the data would be missing because the error aborted the process that loads the zone info. The zone reload is only done on a Restart iC3 and not when HA is restarted. 

Did you see any issues if you restart HA?

**Comment by a120578270** [comment]
After HA was started, version 2.2 of icloud3 was normal and no error was reported. However, when I called icloud in HA to restart the service, I reported an error and the icloud program was terminated. You can call this service in HA and see if it also reported an error.
![image](https://user-images.githubusercontent.com/58241282/82881306-1d024e80-9f72-11ea-8c97-e1dc897a2489.png)

**Comment by gcobb321** [comment]
I’ve updated iCloud3 v2.2.0 (rc2) that fixes the zone loading issue. It’s available for download on the GitHub iCloud3 repository. Let me know if you have any other issues with this problem.

**Comment by a120578270** [comment]
2.2.0rc2 version after many calls to restart the service test after this error does not know whether there is an impact, it looks normal on the surface!

2020-05-27 10:01:20 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2629, in _request_iosapp_location_update
    if self.iosapp_location_update_secs.get(devicename) > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2020-05-27 10:01:20 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] Lb (iphone) iCloud3 Error > An error was encountered processing device `location`request - '>' not supported between instances of 'NoneType' and 'int'
2020-05-27 10:01:20 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2629, in _request_iosapp_location_update
    if self.iosapp_location_update_secs.get(devicename) > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2020-05-27 10:01:20 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] Lb (iphone) iCloud3 Error > An error was encountered processing device `location`request - '>' not supported between instances of 'NoneType' and 'int'

**Comment by gcobb321** [comment]
The above error is one that should never occur but it obviously did. I have added a check for this condition to catch it if it does. The process that was going on when it occurred was formatting an information message to be added to the Event Log.

Yes, the Event Log shows when the device was last located (and the age) in a number of entries -- with the Results of the update, after a trigger or NextUpdateTimeReached event, when the device is authenticated and a few others.

I'll have rc4 available by tomorrow that fixes some minor issues and makes the Event Log easier to review by eliminating the duplicate state/zone/interval/distance lines.

**Comment by gcobb321** [comment]
Closed because of release candidate updates
