### ISSUE TITLE
[iCloud v. 3.0.5.9] HA crashes because iCloud3 sqlite3 error / Waze not available (?)

### ISSUE THREAD

**Issue by ambiman** [gcobb321/icloud3#374]
Today my HA instances crashed and it seems to be related to the iCloud3 integration and the unavailability of Waze(?) maybe:
At least i see in the log a lot of these meessages:

```
09-14 12:38:31 ------ ⡇ my_device_2_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:38:37 ------ ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:38:51 ICLOUD ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:38:51 ------   my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:39:06 ICLOUD ⡇ my_device_2_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:39:06 ICLOUD ⡇ my_device_2_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:39:10 ICLOUD ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:39:12 ------   my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:39:26 ICLOUD ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:39:32 ------   my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:40:01 ------ ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:41:27 1stLOC ⡇ my_device_2_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:41:33 1stLOC ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:41:36 MOBAPP ⡇ my_device_2_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:41:39 MOBAPP ⡇ my_device_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
09-14 12:42:06 MOBAPP ⡇ my_device_2_icloud3 > Waze Route Error > Problem connecting to Waze Servers. Distance will be calculated, Travel Time not available
```

home-assistant.log.fault basically states: 

`Fatal Python error: Segmentation fault`

Icloud3-log:

```
09-14 12:40:15 ICLOUD ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                          ⡇   MY_DEVICE_ICLOUD3, ICLOUD, CURRZONE-NOT_HOME, NEXT UPDATE TIME REACHED
                                          ⡇⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂
09-14 12:40:15 ICLOUD ⡇ my_device_icloud3 > Retrying > Last update not completed
09-14 12:40:15 ICLOUD ⡇ my_device_icloud3 > Zone > Away(1) > StatZon1(1)-996m, StatZon1(1)-996m, StatZon1(1)-996m, StatZon1(1)-996m, StatZon1(1)-996m, StatZon1(1)-996m, StatZon1(1)-996m, StatZon1(1)-996m, Home(1)-1.32km, School-2.31km, Work-52.0km, GPS-(<redacted>, <redacted>/±4m)
09-14 12:40:15 ICLOUD ⡇ Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/waze_history.py", line 354, in _get_all_records
    self.cursor.execute(sql)
sqlite3.ProgrammingError: Recursive use of cursors not allowed.
09-14 12:41:19

```

HA-Core log:

```
[2024-09-14 12:35:56.395 ERROR (SyncWorker_41) [custom_components.icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/waze_history.py", line 354, in _get_all_records
    self.cursor.execute(sql)
sqlite3.ProgrammingError: Recursive use of cursors not allowed
[2024-09-14 12:40:15.799 ERROR (SyncWorker_41) [custom_components.icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/waze_history.py", line 354, in _get_all_records
    self.cursor.execute(sql)
sqlite3.ProgrammingError: Recursive use of cursors not allowed
[12:40:59] INFO: ESC[32mHome Assistant Core finish process exit code 256
[12:40:59] INFO: ESC[32mHome Assistant Core finish process received signal 11

```

**Comment by gcobb321** [comment]
I’ll take a look at the Waze data base retry and those error messages. You can turn Waze off in the _Configuration >  Waze Route Time and Distance_ screen (second menu page). Try disabling the. Waze History first. You should not have to restart HA but it might be a good idea to do that if the errors continue. Reenable it later to see if Waze is back online

**Comment by ambiman** [comment]
Thanks for the fast reply. I will do that. 

Let me know in case you need any additional information.

And again thanks for his great integration!

**Comment by gcobb321** [comment]
Closing due to no activity and the release of v3.1.5
