### ISSUE TITLE
2.2 a new error was found in version 2.2. I wonder what caused it

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#38]
2020-05-26 22:00:25 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2515, in _refresh_pyicloud_devices_location_data
    api_devices = self.api.devices
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 374, in devices
    service_root, self.session, self.params, self.with_family
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 429, in __init__
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 446, in refresh_client
    "deviceListVersion": 1,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 74, in request
    response = super(PyiCloudSession, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

**Comment by gcobb321** [comment]
This one is real strange. It looks like iCloud3 requested a location update which was passed into the pyicloud interface program and HA lost the web service connection and it went downhill from there. I don’t even know where to look for this problem. Let me know if this was a one time event or happens again. I’ll see if any error trapping code will take care of it. 

Where are you located?

**Comment by a120578270** [comment]
![image](https://user-images.githubusercontent.com/58241282/82968166-42896980-9fff-11ea-8791-30d074958237.png)
It seems that the last located time has not been updated

**Comment by gcobb321** [comment]
Does the Event Log screen show any info about when the location was done? Or does it show locations discarded. The debug button on the Event Log will add a lot of info about what goes on. Maybe that will help.

**Comment by gcobb321** [comment]
Release Candidate 4 is now available. See the Release Candidate Change Log file for information on the changes. Download it [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.2.0-rc4)

**Comment by gcobb321** [comment]
Closed because of release candidate updates
