### ISSUE TITLE
iCloud3 v3.1 ➤ Questions & Answers

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#384]
**Post any questions you have to this issue. Create a new issue if you are having problems.**

**Comment by B-Hartley** [comment]
Hi,
Just upgraded to 3.1
Seem to be having problems.

1. Am I supposed to put something into "TOTP Key" field on the apple account screen.
2. How can i delete all config stoed by icloud3 so I can start again with a clean install.


thanks

**Comment by gcobb321** [comment]
Topt is not used yet. Select delete device on the devices list screen. You will have an option to delete all of them.

Gary Cobb, aka geekstergary
________________________________

**Comment by B-Hartley** [comment]
When I go into the icloud devices screen I get "unknown error occurred" so I can't do it from there.
Is there a "back end" way to remove all the data ?

**Comment by gcobb321** [comment]
That’s not good. Go to HA Settings > System (I think) and somewhere you can display the errors in the HA log file.  Anything related to iCloud3 would be helpful.

After that, you can delete the ‘.storage/icloud3/configuration’ file and restart HA


Gary Cobb, aka geekstergary
________________________________

**Comment by B-Hartley** [comment]
Yes, I'd just found the icloud3 folder in .storage/

Errors in log are:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 532, in async_step_menu_0
    return await self.async_step_menu(user_input, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 610, in async_step_menu
    return await self.async_step_device_list()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 2714, in async_step_device_list
    await self._build_mobapp_entity_selection_list()
  File "/config/custom_components/icloud3/config_flow.py", line 3927, in _build_mobapp_entity_selection_list
    Device = Gb.Devices_by_devicename[devicename]
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'xxxxx_iphone'
```

xxxxx was the name on one of my family sharing members.
I'd removed the apple account and made the devices inactive.
I couldn't then get to them to change them back.

Deleted config, restarting and trying again.

Thanks

**Comment by gcobb321** [comment]
I’ll some error checking to catch that error

Gary Cobb, aka geekstergary
________________________________

**Comment by dodgydd** [comment]
3.1 seems to be working for me, thank you very much for your efforts.

**Comment by B-Hartley** [comment]
Still can't get it to setup.
Wiped config.

Setup again.
Sometimes it says 0 of 10 icloud devices tracked.
sometimes is says 0 of 27 icloud devices tracked.

But I can't enabled any of them.

not sure if this is related ?
```
2024-11-04 19:28:20.792 WARNING (MainThread) [custom_components.localtuya.common] [bf2...t8f] Failed to connect to 192.168.21.217: [Errno 113] Connect call failed ('192.168.21.217', 6668)
2024-11-04 19:28:28.219 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 332, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3003, in async_create_flow
    return handler.async_get_options_flow(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 122, in async_get_options_flow
    Gb.OptionsFlowHandler = iCloud3_OptionsFlowHandler()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 365, in __init__
    self.initialize_options()
  File "/config/custom_components/icloud3/config_flow.py", line 472, in initialize_options
    self._initialize_self_PyiCloud_fields_from_Gb()
  File "/config/custom_components/icloud3/config_flow.py", line 496, in _initialize_self_PyiCloud_fields_from_Gb
    self.username = conf_apple_acct[CONF_USERNAME]
                    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'username'
```

**Comment by i8nemo** [comment]
is there any way to change from mi to km?

**Comment by mobiledude** [comment]
Started all over. deleted all files in .storage for icloud3. Uninstalled the integration and re-installed. unable to login into my apple account: this is the HA log:

`Laatst gelogd: 07:56:38

'AA-NOTSPECIFIED-#0'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1139, in create_Devices_object
    pyicloud_ic3_interface.verify_all_apple_accounts()
  File "/config/custom_components/icloud3/support/pyicloud_ic3_interface.py", line 119, in verify_all_apple_accounts
    Gb.username_valid_by_username[f"AA-NOTSPECIFIED-#{cnt}"]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'AA-NOTSPECIFIED-#0'`


Edit:running latest HA Beta

Update: Solved by resetting apple account

**Comment by malvibra** [comment]
Hello! It's my first configuration, but I keep getting this message: ❌ Entry Error, Invalid Username or Password
Credentials are obviously right. I already have purged all the files from .storage and custom_components folders.

**Comment by gcobb321** [comment]
Did you just install iCloud3 v3 for the first time? If so, have you followed the instructions in the User Guide for setting up iCloud3?. The screen images and some instructions are out of date and have not been updated for v4.1, released a few days ago. The basics are the same and you will have to go by the screens.

**Comment by rh37hd** [comment]
> Started all over. deleted all files in .storage for icloud3. Uninstalled the integration and re-installed. unable to login into my apple account: this is the HA log:
> 
> `Laatst gelogd: 07:56:38
> 
> 'AA-NOTSPECIFIED-#0' Traceback (most recent call last): File "/config/custom_components/icloud3/support/start_ic3.py", line 1139, in create_Devices_object pyicloud_ic3_interface.verify_all_apple_accounts() File "/config/custom_components/icloud3/support/pyicloud_ic3_interface.py", line 119, in verify_all_apple_accounts Gb.username_valid_by_username[f"AA-NOTSPECIFIED-#{cnt}"] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'AA-NOTSPECIFIED-#0'`
> 
> Edit:running latest HA Beta
> 
> Update: Solved by resetting apple account

Can you clarify what you mean by resetting Apple account? I'm encountering the same issues.

**Comment by FlowFrank** [comment]
> Did you just install iCloud3 v3 for the first time? If so, have you followed the instructions in the User Guide for setting up iCloud3?. The screen images and some instructions are out of date and have not been updated for v4.1, released a few days ago. The basics are the same and you will have to go by the screens.

I had the same problem, but then managed to solve it. But I can't add a device, I always get the message below. Same when adding an iPhone.

![Bildschirmfoto 2024-11-05 um 21 25 27](https://github.com/user-attachments/assets/cb9b789e-6e73-4f6f-8c87-2e0dbe042150)

**Comment by GerdRuetten** [comment]
> is there any way to change from mi to km?

Open the configuration dialog from icloud3

Select "MENU > CONFIGURE PARAMETERS MENU ᐳ Format Parameters; Display Text As; Waze Route Distance, Time & History; inZone Intervals; Special Zones; Other Parameters"
<img width="566" alt="image" src="https://github.com/user-attachments/assets/c346383e-8c00-4ffb-bd5b-e81807267b9c">

Select FORMAT SETTINGS ᐳ Log Level; Zone Display Format; Device Tracker State; Unit of Measure; Time & Distance, Display GPS Co
<img width="569" alt="image" src="https://github.com/user-attachments/assets/d91a2932-1754-44d0-bee1-8f0a8652797f">
ordinates

Set UNIT OF MEASUREMENT to Metric
<img width="571" alt="image" src="https://github.com/user-attachments/assets/f33d4abf-4499-41db-bf36-a0df867f84c1">

**Comment by naseemr** [comment]
Hi,
In Add iCloud3 Device windows what is the what is the icloud3 entity id? is it fmshr email? Also I followed the user guide  for new install, but still cant add device from family share

**Comment by enedberg** [comment]
I am also getting "0 of 0" tracked devices and are unable to add new devices.




> > Did you just install iCloud3 v3 for the first time? If so, have you followed the instructions in the User Guide for setting up iCloud3?. The screen images and some instructions are out of date and have not been updated for v4.1, released a few days ago. The basics are the same and you will have to go by the screens.
> 
> I had the same problem, but then managed to solve it. But I can't add a device, I always get the message below. Same when adding an iPhone.
> 
> ![Bildschirmfoto 2024-11-05 um 21 25 27](https://private-user-images.githubusercontent.com/56410024/383303642-cb9b789e-6e73-4f6f-8c87-2e0dbe042150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTA5MzgsIm5iZiI6MTczMDg5MDYzOCwicGF0aCI6Ii81NjQxMDAyNC8zODMzMDM2NDItY2I5Yjc4OWUtNmU3My00ZjZmLThjODctMmUwZGJlMDQyMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDEwNTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZDE4NzUzYTliMjZlMWEzMzIxYTAzNmMwZDM4MzcyZDNmOTY2ZTE3NDE3NjI1N2QxNmUxMTRiOGRlY2QyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6UOMiCDZnRfNgMrRDhZnyJLYLeb5P5n2y2WH5w455no)

**Comment by freddanastrom** [comment]
> I am also getting "0 of 0" tracked devices and are unable to add new devices.
> 
> > > Did you just install iCloud3 v3 for the first time? If so, have you followed the instructions in the User Guide for setting up iCloud3?. The screen images and some instructions are out of date and have not been updated for v4.1, released a few days ago. The basics are the same and you will have to go by the screens.
> > 
> > 
> > I had the same problem, but then managed to solve it. But I can't add a device, I always get the message below. Same when adding an iPhone.
> > ![Bildschirmfoto 2024-11-05 um 21 25 27](https://private-user-images.githubusercontent.com/56410024/383303642-cb9b789e-6e73-4f6f-8c87-2e0dbe042150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTA5MzgsIm5iZiI6MTczMDg5MDYzOCwicGF0aCI6Ii81NjQxMDAyNC8zODMzMDM2NDItY2I5Yjc4OWUtNmU3My00ZjZmLThjODctMmUwZGJlMDQyMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDEwNTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZDE4NzUzYTliMjZlMWEzMzIxYTAzNmMwZDM4MzcyZDNmOTY2ZTE3NDE3NjI1N2QxNmUxMTRiOGRlY2QyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6UOMiCDZnRfNgMrRDhZnyJLYLeb5P5n2y2WH5w455no)

Same issue here, 0 of 0 iCloud devices.
Not a new install, just upgrade to 3.1.

I also get this during startup stage 4 in the event log:
APPLE ACCOUNT NOT LOGGED INTO > A device’s Apple Acct was not logged into and will not be tracked:
- Apple Acct-> Fredrik (fredriks_iphone)
- Apple Acct-> *** (***_iphone)

When updating the login information it seems to be accepted, also accepting the verification code.

**Comment by gcobb321** [comment]
@B-Hartley 
I will be releasing v3.1.1 tomorrow and it fix the problem getting the devices and locations when iCloud3 starts, leading to the '0 of 0' errors. It was a bug that in the authentication routine, caused by deleting the _icloud2.apple_acct_ cookie files, requiring a new authentication. Also a number of other fixes.

**Comment by gcobb321** [comment]
@naseemr 
 The iCloud3 Device Name  is the device_tracker entity you are assigning to the iCloud3 device you want to track. The Apple Account and Mobile App devices to be associated with this device_tracker entity are selected on the next page. (Example: gary_iphone)

I have added this to the v3.1.1 Add Device screen. The process is explained in the iCloud3 Docs.

**Comment by FlowFrank** [comment]
It's been working for me for a few hours. I successfully installed iPhones and Apple Watches. Worked after the last supervisor update.

**Comment by gcobb321** [comment]
### iCloud3 v3.1.1 has been to HACS

Release page is [here](https://github.com/gcobb321/icloud3/releases)

### Change Log - v3.1.1
1. LOCATING DEVICES:
    - Added additional checks to insure the Apple Account location data was refreshed during startup and while configuing iCloud3 settings. Fixed a problem where the location information data from Apple was not being initialized properly.
    - Fixed the location refresh not being done that caused the '0 of 0' to be displayed in the Configure Setting screens, leading to the Apple Account selection lists to not be populated.
    - Fixed some problems where 'Locate All Devices = False' would still locate all the devices in the Apple account
    - Added error checking to make sure the Locate All Devices can not be disabled if there were Family devices that
    were assigned to that Apple account. If it was disabled, they would never be located.
2. UPDATE DEVICE SCREEN - Added (and fixed) the TOOLS - RESET DATA SOURCE(S), DELETE DEVICE(S) option where you can reset the device's Apple Account and Mobile App to default values (None) and fixed a problem deleting devices. Reworked the Apple Account selection list to provide more information and identify setup errors.
3. UPDATE APPLE ACCOUNT USERNAME/PASSWORD SCREEN - Added checks to insure Locating All Devices can not be disabled if there are tracked devices assigned to this account that are in the Family list.
4. OTHER THINGS - Changed several things under the covers.

**Comment by Harry-1976** [comment]
Devices don’t update after a HA restart. I have to reload the integrations to sync them.

**Comment by gcobb321** [comment]
Are there any messages in the _Event Log_? 
Is the Apple account being logged into? Are all devices in the account being displayed in the _Event Log_?
Stages 3-5 provide a lot of detail about how Apple and Mobile App devices are associated with the iCloud3 device. Do you see any notifications? 
When it stops working, what does the _Event Log_ show regarding location updates? 
Are there any error related to iCloud3 in the HA load at Settings > System > Logs?

**Comment by Harry-1976** [comment]
I haven't been able to reproduce it. Must have been something on my end. Sorry for trouble.

**Comment by i8nemo** [comment]
I recently removed all tracked devices and I reinstalled icloud v3 integration.  I can successfully add my icloud credentials, but when it comes to add new devices from my Apple account drop down, nothing is listed with line "all Apple account devices are signed".  Yet no tracked devices are configured.  
![Screenshot_20241125_211626_Home Assistant](https://github.com/user-attachments/assets/8fad017b-464d-4164-a04c-823aa9422c83)

**Comment by gcobb321** [comment]
@i8nemo 
Try exiting the Configure screens and Restart iCloud3 on the _Event Log > Actions >_ if it doesn’t restart, then go back to the _Configure > iCloud3 Devices > Select > Update Device_ screen 
If that doesn’t work,  Try restarting HA and see if they are picked up.

**Comment by i8nemo** [comment]
Unfortunately restart does not correct the issue. I've also have tried deleting and reinstalled both integration and from HACS with HA restart.  Same result.

**Comment by gcobb321** [comment]
@i8nemo 
Apple might not be completely logged into and the family share devices were not picked up. 

There have been errors starting iCloud3 lately where Apple reverted back to the old method of validating passwords. You need to revert to v3.0.5.9 and then reject the Family Sharing in the _Configure > Data Sources-Apple Accts & MobApp _ screen   

See [here](https://github.com/gcobb321/icloud3_v3/issues/375)

**Comment by Kuchiru** [comment]
Hello, i've been using this addon for a while without issues. unfortunately, recently i started having issues.
First I had login issues, this was resolved with downgrading.
Second, i got a new iPhone - restored my backup and set everything up. All entity names are the same for the new phone and i can see the phone report everything correctly via the mobile app. however, icloudv3 states the following:
```
Error, The Mobile App Integration is not installed. The Mobile App will not be used as a data source; location data and zone enter/exit triggers will not be monitored
```
And this is exactly what happens, even the mobile app reports zone changes correctly in home assistant but the icloudv3 integration does not.

What can i do to remedy this?

**Comment by gcobb321** [comment]
@Kuchiru 
That message comes from iCloud3 not being able to find the mobapp device tracker entity associated with the iCloud3 device.
1. Check the Mobile App Integration and make sure the device is listed.
2. go to the iCloud3 _update device_ configuration screen for the device and check the mobile app it is using.
3. Check the Event Log > Stage 4 & 5 for messages and the mobapp device tracker  assignment.

**Comment by Kuchiru** [comment]
@gcobb321
Thank you for the quick response!

It appears that the mobile app device tracker is set properly, the device is also listed in the mobile app integration.

Could this possibly be the cause ?
![image](https://github.com/user-attachments/assets/a25b7d9b-d340-4ce3-a9b4-b83974c6a972)

**Comment by rktr2009** [comment]
New user here, for a wonderful integration. Everything works now, thanks to the developers. A quick question. Does tracking devices through icloud3 affect the device's battery drain? I am just curious as I am seeing battery levels decreasing slightly quicker than it was before using the integraion. I am assuming that is so because of tracking data more than a standard icloud connection. Or is it because it is using also HA companion app for tracking? Thanks.

**Comment by pbix** [comment]
After recovering my HA instance from a backup my Wife's phone showed status of "StatZon1" instead of "Home".
When she left the home and returned it became "Home" as expected.  How can I prevent this in the future?  Where is "StatZon1" coming from?  I have no zones defined either in the HA App or in the iCloud3 integration.

![image](https://github.com/user-attachments/assets/645dd84f-8ab4-4844-9ec3-3dffcc200424)

**Comment by B-Hartley** [comment]
Statzon is just a temporary stationery zone. So she was still
But believed to not be at home. These zones allow updates to trigger location changes when you leave that statzon (I believe)

I'd advise that if you restore a backup. You check and manually fix the home status. 

Presumably you don't restore backups often ?

**Comment by gcobb321** [comment]
@rktr2009 
You might see a little more battery drain because Apple is locating the device more often than it usually does. When iCloud3 requests the location of a device, all of the devices in the account are located. The mobile app will not have an impact. iCloud3 monitors the mobile app entities to see when the location changed and rarely asks for one.

**Comment by gcobb321** [comment]
@pbix 
When iCloud3 updates the sensors, it also keeps a copy of the sensors value so it can reset those values if HA restarts. When you did the restore, the sensor value restore file was also restored, thus the old values were initially displayed. The first location request should bring them back to their current value. The stationary zones should also be reset during that time.

if you see locations that are incorrect after restarting or restoring, go to _Event Log > Actions_ and select _Restart iCloud3_ or _Locate all devices using iCloud_ to refresh the locations.

**Comment by pbix** [comment]
> @pbix When iCloud3 updates the sensors, it also keeps a copy of the sensors value so it can reset those values if HA restarts. When you did the restore, the sensor value restore file was also restored, thus the old values were initially displayed. The first location request should bring them back to their current value. The stationary zones should also be reset during that time.
> 
> if you see locations that are incorrect after restarting or restoring, go to _Event Log > Actions_ and select _Restart iCloud3_ or _Locate all devices using iCloud_ to refresh the locations.

StatZon1 has no meaning to me and I never intentionally created it.  Only one of the devices we have is showing the StatZon1 after reset.    I would just like the devices to show Home or Away.  I do not see how I can locate the "_Event Log > Action" selection as you mention.  Is this somewhere under the iCloud3 configuration?  I do not see it anywhere there.  How can I eliminate StatZon1?

**Comment by B-Hartley** [comment]
Event log action refers to the icloud3 card that is included in the integration to monitor and control things. 

Statzon1 is not optional it's part of how icloud3 works. 
If you just want home and away then then a template sensor on top of the device tracker might make sense.

**Comment by gcobb321** [comment]
iCloud3 v3.1.5 beta 3 prerelease update.

Unzip the following zip file into the _custom_components/icloud3_ directory and restart HA.

[icloud3 v3.1.5b3.zip](https://github.com/user-attachments/files/18623838/icloud3.v3.1.5b3.zip)

### Release Notes - v3.1.5b3 (1/31/2025)
#### 🐛 Bug Fixes
- A problem connecting to the Internet is detected within 2-minutes. A notification is sent to the Apple accounts primary device and status messages are displayed on the Event log. The Internet status is monitored and tracking tracking resumes when it comes back online.
- A location request was sent incorrectly to Apple when logging into or adding a new Apple Account. This caused an incorrect _Invalid Username/Password_ message to be displayed and communication with the Apple account stopped.
- The _Enter/Request Verification Code_ screen was not displaying correctly if there were no Apple accounts that needed to be verified or the Apple account was deleted.

#### 🎉 Improvements and New Features
- Improved - Internet connections errors are now detected and monitored. iCloud3 will pause all tracking until the Internet is back up. A status message is displayed in the Event log and a message will be sent to an iCloud3 device using the Mobile App that Home Assistant is Offline.
- Improved - Renamed and reorganized the _Configure > Tracking Parameters_ screen and _Field Formats & Event Log Parmaeters_ screens.
- New - The _Picture Directory Filter_ can now be updated from the _Update Device_ screen _Picture Selection List_.
- New - If no picture is selected for the Device (=None), the Device's icon that will be displayed can now be selected from Home Assistant's 'mdi:' icon image list (default=mdi:account).
