### ISSUE TITLE
iCloud3 v3.1.2➤ A new release of iCloud3 v3 is available - 11/8/2024

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#389]
### Change Log - v3.1.2 - 11/8/2024
1. INITIAL SETUP (Fixed) - This fixed some issues related an initial install where there are no apple accounts or where the iCloud3 Apple account's first configuration file entry was blank.. This fixes the error message:
    ```
    File "/config/custom_components/icloud3/config_flow.py", line 1974, 
        in async_step_update_apple_acct
    self._update_conf_apple_accounts(self.aa_idx, user_input)
    File "/config/custom_components/icloud3/config_flow.py", line 2055, 
        in _update_conf_apple_accounts
    if Gb.conf_apple_accounts[0][CONF_USERNAME] == '':
    ~~~~~~~~~~~~~~~~~~~~~~^^^
    IndexError: list index out of range
    ```

### Change Log - v3.1.1 - 11/7/2024
1. LOCATING DEVICES:
    - Added additional checks to insure the Apple Account location data was refreshed during startup and while configuing iCloud3 settings. Fixed a problem where the location information data from Apple was not being initialized properly.
    - Fixed the location refresh not being done that caused the '0 of 0' to be displayed in the Configure Setting screens, leading to the Apple Account selection lists to not be populated.
    - Fixed some problems where 'Locate All Devices = False' would still locate all the devices in the Apple account
    - Added error checking to make sure the Locate All Devices can not be disabled if there were Family devices that
    were assigned to that Apple account. If it was disabled, they would never be located.
2. UPDATE DEVICE SCREEN - Added (and fixed) the TOOLS - RESET DATA SOURCE(S), DELETE DEVICE(S) option where you can reset the device's Apple Account and Mobile App to default values (None) and fixed a problem deleting devices. Reworked the Apple Account selection list to provide more information and identify setup errors.
3. UPDATE APPLE ACCOUNT USERNAME/PASSWORD SCREEN - Added checks to insure Locating All Devices can not be disabled if there are tracked devices assigned to this account that are in the Family list.
4. OTHER THINGS - Changed several things under the covers.

**Comment by enedberg** [comment]
Still getting 0 of 0 devices on a new, clean install.

I see this in my logs:

`This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/support/pyicloud_ic3.py:827
integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 19:19:20 (2 occurrences)
Last logged: 19:25:03

even, Authentication Failed, Python SRP Library Credentials Error. The Python module that creates the Secure Remote Password hash key has calculated an incorrect value for a valid Username/Password. Try changing the Password to see if the Apple Acct can be logged into. ErrorCode-401
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 827, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: even, Authentication Failed, Python SRP Library Credentials Error. The Python module that creates the Secure Remote Password hash key has calculated an incorrect value for a valid Username/Password. Try changing the Password to see if the Apple Acct can be logged into. ErrorCode-401`

**Comment by gcobb321** [comment]
See my note [here](https://github.com/gcobb321/icloud3_v3/issues/341#issuecomment-2458440469). It describes what is going on. But you will need to change your password. That has worked for others with the same problem

**Comment by enedberg** [comment]
> See my note [here](https://github.com/gcobb321/icloud3_v3/issues/341#issuecomment-2458440469). It describes what is going on. But you will need to change your password. That has worked for others with the same problem

Thank you, that solved the problem. It also flushed all my app specific passwords, so I had to set them up again. 

Thank you for your work

**Comment by gcobb321** [comment]
Be sure to send me your old password That failed
