### ISSUE TITLE
Constant error in 15 minute retry

### ISSUE THREAD

**Issue by N3rdix** [gcobb321/icloud3#397]
Hi Gary,
although my watch is being tracked correctly (I love this integration 😍) I get frequent errors since a few days within the new 503 retry mechanism.
Anything I can do to track down the error?

When it starts I only see these errors in the log every 15 minutes:

```
Logger: custom_components.icloud3
Quelle: custom_components/icloud3/support/config_file.py:396
Integration: iCloud3 v3 (Dokumentation, Probleme)
Erstmals aufgetreten: 15. November 2024 um 22:45:00 (76 Vorkommnisse)
Zuletzt protokolliert: 08:00:00

'watch_ultra_tobias' is not in list
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/config_file.py", line 396, in conf_apple_acct
    conf_apple_acct_idx = conf_apple_acct_username.index(idx_or_username)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'watch_ultra_tobias' is not in list
```

```
Logger: custom_components.icloud3
Quelle: custom_components/icloud3/support/pyicloud_ic3_interface.py:87
Integration: iCloud3 v3 (Dokumentation, Probleme)
Erstmals aufgetreten: 15. November 2024 um 22:45:00 (76 Vorkommnisse)
Zuletzt protokolliert: 08:00:00

'password'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 243, in _polling_loop_5_sec_device
    self._main_5sec_loop_special_time_control()
  File "/config/custom_components/icloud3/icloud3_main.py", line 651, in _main_5sec_loop_special_time_control
    pyicloud_ic3_interface.retry_apple_acct_login()
  File "/config/custom_components/icloud3/support/pyicloud_ic3_interface.py", line 87, in retry_apple_acct_login
    password = conf_apple_acct[CONF_PASSWORD]
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'password'
```

EDIT: the errors vanish after a HA restart, disabling the integration in contrast did not stop the errors.

**Comment by thenoid** [comment]
Ditto.

Getting similar errors and 503s
```
homeassistant  | 2024-11-23 20:07:40.734 ERROR (SyncWorker_9) [custom_components.icloud3] house, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
homeassistant  |     self.authenticate()
homeassistant  |   File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
homeassistant  |     raise PyiCloudFailedLoginException(err_msg)
homeassistant  | custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: house, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
```

**Comment by N3rdix** [comment]
> Ditto.
> 
> Getting similar errors and 503s
> 
> ```
> homeassistant  | 2024-11-23 20:07:40.734 ERROR (SyncWorker_9) [custom_components.icloud3] house, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
> homeassistant  | Traceback (most recent call last):
> homeassistant  |   File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
> homeassistant  |     self.authenticate()
> homeassistant  |   File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
> homeassistant  |     raise PyiCloudFailedLoginException(err_msg)
> homeassistant  | custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: house, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
> ```

Same error for me since this morning as well, seems to affect everything. Even requesting a verification code is not possible

**Comment by marceloaf** [comment]
Me too

**Comment by christian-persson** [comment]
Same for me.

**Comment by zakoman81** [comment]
I solved it with downgrade to V3.0.5.9
Core 11.1

Best regards, Thomas

**Comment by gcobb321** [comment]
There are several issues related to this. My comments from earlier today on another one

I am getting the same 503 Connection Error and have no idea why. 

It appears that Apple has made some changes once again, this time rejecting password requests made using the Secure Password Request protocol it implemented in October. I have changed the title to reflect the issue. 

The problem is not on the iCloud3 end, it is on the Apple end where a 503 response code is being returned when iCloud3 sends a request to validate the password. Apple is basically saying “I’m not going to do that”. I don’t know if it will do it later or they have made some change that will require an update. There is no need to reset the config, reinstall or changing passwords at this time. 

There is nothing that can be done at this time but wait to see if they open it up again.

**Comment by gcobb321** [comment]
@zakoman81 
That version used the password authentication method prior to Apple implementing the SRP password protocol at the end of October. Looks like they went back to the older version. I will check it out.

**Comment by michaelblight** [comment]
> V3.0.5.9

Reverting to this version (until it works again) fixed it for me too, but it showed "not logged in". I had to tick "family sharing" again and log in again - just asking for another verification code did not work.

**Comment by gcobb321** [comment]
@michaelblight 
_Event Log > Actions > Restart iCloud3_ might reset iCloud and refresh the Apple devices. Review _Event Log_ Stage 4 from the Apple acct devices iCloud3 received when it started up

**Comment by gcobb321** [comment]
Closing due to no activity and the release of v3.1.5
