### ISSUE TITLE
Several concurrent errors 

### ISSUE THREAD

**Issue by fi-sch** [gcobb321/icloud3#40]
Hi!

I'm experiencing concurrent several errors from time to time. Usually they appear a few times a day but I'm not sure what is the cause of that behaviour. I'm seeing since around last 2-3 weeks. I did not see them before.

I'm running latest version of HA (0.110.6) and icloud3 component (v2.1).
Here's my config:
```
device_tracker:
  - platform: icloud3
    username: !secret icloud_usr
    password: !secret icloud_pass
    track_devices:
      - Filip > *****@*******.**
    unit_of_measurement: km
    distance_method: calc
    stationary_still_time: 8
    old_location_threshold: 2
    create_sensors: nupdt
```

And here are the errors:
```
Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/pyicloud_ic3.py:844 
Integration: icloud3 (documentation) 
First occurred: 14:05:30 (1 occurrences) 
Last logged: 14:05:30

'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2552, in _get_fmf_updated_location_data
    locations = fmf.locations
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 862, in locations
    return self.data.get('locations')
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 856, in data
    self._data = self.refresh_data()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 844, in refresh_data
    self.response = req.json()
AttributeError: 'NoneType' object has no attribute 'json'
```

```
Logger: custom_components.icloud3.pyicloud_ic3.http
Source: custom_components/icloud3/pyicloud_ic3.py:862 
Integration: icloud3 (documentation) 
First occurred: 14:05:30 (1 occurrences) 
Last logged: 14:05:30

Failed to parse response with JSON mimetype
```

```
Logger: custom_components.icloud3.pyicloud_ic3.http
Source: custom_components/icloud3/pyicloud_ic3.py:123 
Integration: icloud3 (documentation) 
First occurred: 14:05:30 (1 occurrences) 
Last logged: 14:05:30

local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 123, in request
    content_type = response.headers.get('Content-Type', '').split(';')[0]
UnboundLocalError: local variable 'response' referenced before assignment
```

```
Logger: custom_components.icloud3.pyicloud_ic3.http
Source: custom_components/icloud3/pyicloud_ic3.py:113 
Integration: icloud3 (documentation) 
First occurred: 14:05:30 (1 occurrences) 
Last logged: 14:05:30

('Connection aborted.', OSError("(110, 'ETIMEDOUT')"))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (110, 'ETIMEDOUT')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(110, 'ETIMEDOUT')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 113, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(110, 'ETIMEDOUT')"))
```

Thanks!

**Comment by gcobb321** [comment]
The iCloud3 Release Candidate has been updated and can be downloaded here. See the Change Log-Release Candidates a list of the items that were addressed in this Release Candidate.

The first item below is an important change that corrects the iOS App sensor monitoring function that generates the zone enter/exit and location change triggers which were not being detected after the iOS App and HA were updated.

The only programs that were updated are:

- device_tracker.py
- icloud3-event-log-card.js

------------------


I'm closing this issue. If you continue to have problems after RC7, please open another issue.
