### ISSUE TITLE
503 issues again 

### ISSUE THREAD

**Issue by nivek1612** [gcobb321/icloud3#400]
I thought this had been fixed in the latest version but as of this morning I'm seeing these two errors

Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: kev, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503

kev, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: kev, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503

Tried restarting, reinstalling etc but still getting the above error.

Attempts to re-request validation code from apple get no response.

**Comment by enedberg** [comment]
Same problem here

I don't know if it is related, but I updated HA to 2024.11.3 and my iPhone til 18.1.1 this morning. Now iCloud3 is not updating and it does not find the devices in my account. All devices are marked with "not in Apple- acct". When I go to configure the integration and devices it says '4 of 0 devices tracked'.

I just updated my iCloud password some weeks ago to get iCloud3 working again.

This is from my log:
```
This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/support/pyicloud_ic3.py:824
integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 13:17:36 (6 occurrences)
Last logged: 16:20:55

even, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: even, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
```

**Comment by mpipeling** [comment]
Ditto with same log info below of "Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503"

tried thus far:
reload integration followed by 2 full system reboot
revert to HA 2024.11.1 & try same
change Apple password (tracking remains intake via FindMy...)

fear may be a change in 'formula' for the generation of secure hash key.... (?)


11-24 10:35:59 iCloud3 v3.1.3
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: mpipeling, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503

11-24 10:35:59 STAGE4  Apple Acct > mpipel…, Login Successful
11-24 10:35:59 STAGE4  Apple Acct > mpipeling, All Devices Located
11-24 10:35:59 STAGE4  Apple Acct > mpipel…, Data for a Device not returned from Apple
                            • Matt's iPhone XS (matt_s_iphone_xs) > Device-Matt's iPhone XS

**Comment by mx-dimadon11** [comment]
Also a mistake

This error occurred in the user integration.

User: custom_components.icloud 3
Source: custom_components/icloud3/support/pyicloud_ic3.py:824
Integration: iCloud 3v3 (recordings, applications)
First message: 19:36:36 (4 messages)
Last message: 19:50:28

 Authentication failed, connection failed, and data for verifying a secure password were not returned to Apple. The error code is 503
Tracking (last call):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py ", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py ", line 824, when authenticating
    causes an exception PyiCloud FailedLoginException(err_msg)
custom_components.icloud 3.support.pyicloud_ic3.PyiCloudFailedLoginException: Authentication error, connection error, Data for verifying a secure password was not returned to Apple. The error code is 503

**Comment by mx-dimadon11** [comment]
The error appeared today. Although my account was monitored, but my wife was not. Installed on up to version 2024.11.3. IOS 18.1.1

**Comment by gcobb321** [comment]
I am getting the same 503 Connection Error and have no idea why. 

It appears that Apple has made some changes once again, this time rejecting password requests made using the Secure Password Request protocol it implemented in October. I have changed the title to reflect the issue. 

I posted this on the _v3 development repository earlier today. 

The problem is not on the iCloud3 end, it is on the Apple end where a 503 response code is being returned when iCloud3 sends a request to validate the password. Apple is basically saying “I’m not going to do that”. I don’t know if it will do it later or they have made some change that will require an update. There is no need to reset the config, reinstall or changing passwords at this time. 

There is nothing that can be done at this time but wait to see if they open it up again.

**Comment by lorenzo-torregiani** [comment]
![IMG_1499](https://github.com/user-attachments/assets/6e7476b0-982a-4d44-8702-5321b929cfe3)
Hello, I believe I have the same problem as you. I ask for further confirmation if it does the same for you, as it says I have 0 devices.

**Comment by markthebest12** [comment]
To narrow further, I’m pretty certain the 503s are triggered by updating to iOS 18.1.1 

I have three phones configured identical in HA, the two upgraded to 18.1.1 are getting 503s while the phone still on 18.1 is working fine in HA

**Comment by mx-dimadon11** [comment]
My wife's 18.1 is still standing and not working

**Comment by rjosborne** [comment]
For anybody only looking at this issue, a downgrade to V3.0.5.9 seems to have solved it for at least some people (including me).

**Comment by mpipeling** [comment]
can confirm downgrading below v3.1 (e.g. v3.0.5.9) allows login/authentication & all devices actively monitored/tracked again

11-24 17:26:07 [start_ic3_co:0216] STAGE4   iCloud Account > Logging Into- (mp.......@gm.......)
11-24 17:26:07 [pyicloud_ic3:0199] STAGE4 ❗Connecting to and Authenticating iCloud Location Service Interface (startup)
11-24 17:26:07 [pyicloud_ic3:0536] STAGE4 ❗Initialize PyiCloud Service, establish iCloud Location Services connection
11-24 17:26:07 [pyicloud_ic3:0927] STAGE4 ❗Read Cookies from /config/.storage/icloud/mpipelinggmailcom
11-24 17:26:07 [pyicloud_ic3:0494] STAGE4 ❗AUTHENTICATING iCloud Account Access,  (mp.......@gm.......), startup
11-24 17:26:07 [pyicloud_ic3:0618] STAGE4 ❗Authenticating account  (mp.......@gm.......) with token
11-24 17:26:09 [pyicloud_ic3:0685] STAGE4 ❗Authenticate.authenticate_with_token > Successful
11-24 17:26:09 [pyicloud_ic3:0651] STAGE4 ❗Authentication completed successfully, method-Token
11-24 17:26:09 [pyicloud_ic3:1580] STAGE4 ❗Create RawData_famshr object Matt's iPhone

**Comment by eskholm** [comment]
> For anybody only looking at this issue, a downgrade to V3.0.5.9 seems to have solved it for at least some people (including me).

Same. Downgrade to 3.0.5.9 worked here as well.

**Comment by woody166** [comment]
Same issue here.  Downgraded to 3.0.5.8 and seems to be working fine now.

**Comment by nivek1612** [comment]
Downgrade to 3.0.5.9 gets things working but note I have this error in the logs 

name 'xtra_attrs' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 394, in _get_extra_attributes
    xtra_attrs[f"{'-'*5} ICLOUD3 CONFIGURATION {'-'*19}"] = ''
    ^^^^^^^^^^
NameError: name 'xtra_attrs' is not defined. Did you mean: 'extra_attrs'?

**Comment by easez88** [comment]
Just confirming, the issue is caused by the latest update. I updated my phone today and it stopped working. Downgrading worked for me as well

**Comment by ahentsch** [comment]
I have the same issue here **after updating HA yesterday on core_2024.11.3**

( original comment had a typo in version)

**Comment by enedberg** [comment]
Redownload version 3.0.5.9 from HACS and logging inn again worked for me too.

**Comment by nivek1612** [comment]
@gcobb321 I'm back on 3.0.5.9 for now which gets it working but any tips to get rid of this error from the logs ? 

name 'xtra_attrs' is not defined
Traceback (most recent call last):
File "/config/custom_components/icloud3/device_tracker.py", line 394, in _get_extra_attributes
xtra_attrs[f"{'-'*5} ICLOUD3 CONFIGURATION {'-'*19}"] = ''
^^^^^^^^^^
NameError: name 'xtra_attrs' is not defined. Did you mean: 'extra_attrs'?


Hope the cruise is fun :-)

**Comment by pdawg17** [comment]
Interesting, I downgraded to 3.0.5.9 and it still does NOT work...I'm on HA 2024.11.3

**Comment by gcobb321** [comment]
@nivek1612 
The v3.0.5.9 release on GitHub was to fix that error. Unless HACS is not getting the correct code. 

Edit the _icloud3/device_tracker.py_ file. 
Change line 394.
    From-
`
            xtra_attrs[f"{'-'*5} ICLOUD3 CONFIGURATION {'-'*19}"] = ''
`
    To -
`
            extra_attrs[f"{'-'*5} ICLOUD3 CONFIGURATION {'-'*19}"] = ''
`

Save the file
Restart HA

**Comment by nivek1612** [comment]
> @nivek1612 The v3.0.5.9 release on GitHub was to fix that error. Unless HACS is not getting the correct code.
> 
> Edit the _icloud3/device_tracker.py_ file. Change line 394. From- `xtra_attrs[f"{'-'*5} ICLOUD3 CONFIGURATION {'-'*19}"] = ''` To - `extra_attrs[f"{'-'*5} ICLOUD3 CONFIGURATION {'-'*19}"] = ''`
> 
> Save the file Restart HA

Re-download v3.0.5.9  from HACS all good again

**Comment by paulhobbel** [comment]
@gcobb321 is there a possibility to release a patch that reverts back to the old authentication method. I am indeed able to get 3.0.5.9 to work, but I have an issue where two devices have the same name, 3.0.X can’t deal with duplicated device names, but 3.1 had fixed this. If there’s any way I can help or open a PR that is also fine by me 😁

**Comment by LioBoul** [comment]
Hi all,

Same here :-(
How to return to 3.0.5.9?
I have red/l this version on HACS but 3.1 is already active, Idem if I delete icloud and restart HA.

**Comment by gcobb321** [comment]
@LioBoul
See [here](https://github.com/gcobb321/icloud3_v3/issues/378#issue-2695328791) for more information about this problem

**Comment by LioBoul** [comment]
@gcobb321 
I followed the procedure correctly and that's what I was already doing.
It stays in 3.1 when I reinstall the icloud v3 integration.
Bizaaaarre...

![Capture d’écran 2024-11-29 172433](https://github.com/user-attachments/assets/91faed5d-978b-4a85-aef2-7a3b1191fc7c)

**Comment by LioBoul** [comment]
It's ok, it worked but I had to delete everything via integrations, HACS and manually the folders in .storage. It's ok ! Tks :-)

**Comment by ahentsch** [comment]
Hi, Any idea why I get issues
![IMG_5419](https://github.com/user-attachments/assets/75658f00-2c15-48fa-9b1f-bbe6aa09b637)
![IMG_5418](https://github.com/user-attachments/assets/85f0de15-2f39-4b9b-8c3a-0e6955bd0d65)
![IMG_5417](https://github.com/user-attachments/assets/8685fc98-3497-441d-81a1-8dcf408e684b)
 after downgrading and reinstalling 3.0.5.9 See Screenshots

**Comment by RadDip** [comment]
Any idea when this will be fixed with new version?

**Comment by gcobb321** [comment]
I have been on a cruise off the west coast of Africa since Apple made the change and return home on 12/10. I’m hoping to have an update by 12/17. I haven’t been able to log into my account from the ship so updates from here were not possible. There will be a few m maintenance items also in the next release.

**Comment by woody166** [comment]
any update on this please.

**Comment by gcobb321** [comment]
I have everything now working on my test systems at home. The old password verification works fine. I got the new password SRP method working yesterday but I have been experiencing verification code requests about every 6-hours with the new password SRP and am trying to figure out what is going on with that before I release it. All of the other changes I have made are now complete and I will issue an update later this week. With or without the new password SRP authentication method.

**Comment by gcobb321** [comment]
V3.1.4.1 has been released and should be available on hacs

**Comment by nivek1612** [comment]
It is and works as expected thanks for the work

**Comment by gcobb321** [comment]
Closing due to no activity and the release of v3.1.5
