### ISSUE TITLE
Watch battery charge is wrong and has shown the same number for 5 days

### ISSUE THREAD

**Issue by bkr1969** [gcobb321/icloud3#404]
Why is this not updating?  Have reloaded, uninstalled and re-installed. No change.

![image](https://github.com/user-attachments/assets/99a57563-5479-44e2-af1f-286a736b9a5c)

**Comment by bkr1969** [comment]
Actually, nothing seems to be working correctly.  My watch is listed at a totally different location than my phone (they are the same in Find My).  Neither the watch nor the phone are showing correct charge or charging states.  And I don't understand this screen that says my phone and my watch are not in my Apple account.  I have now reinstalled twice with no changes.  Please clarify.

![image](https://github.com/user-attachments/assets/2d32934d-cfaf-4584-870a-ece488574c04)

This from the logs:

This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/helpers/messaging.py:497
integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 09:16:29 (2 occurrences)
Last logged: 09:16:29

iCloud3 Device Configuration Error > Brian's Phone (brian_s_iphone_13), iCloudDevice-Brian's iPhone 13, Not in Apple Acct-briankredmond1969@…………
iCloud3 Device Configuration Error > Apple Watch (brian_s_apple_watch), iCloudDevice-Brian's Apple Watch, Not in Apple Acct-briankredmond1969@…………


This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/support/pyicloud_ic3.py:824
integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 09:16:28 (3 occurrences)
Last logged: 09:16:29

briankredmond1969, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
    ~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: briankredmond1969, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503

**Comment by bkr1969** [comment]
Apple authentication issue.  Downgraded and it's working.
