### ISSUE TITLE
Unknown error occurred 3.1.4

### ISSUE THREAD

**Issue by karlnewick** [gcobb321/icloud3#408]
I installed version 3.1.3, then went back to 3.0.59 when the auth issues started to happen. That never worked for me so I waited for this version to be released.

I tried to reload and pick version 3.1.4, I could only see 3.1.3. So I downloaded the zip and manually installed it over the clean version 3.1.3. I had issues with the Apple codes not being taken, I removed everything related in the .storage/icloud3 & icloud3.apple_acct. Restarted the account setup and I got passed the username and password and code requests. I see the list of devices 👍 

Then tried to configure and add a device to track, with and without the HA Mobile App. I get the "Unknown error occurred", so I turned on debug logging. Every time I try to add a device I get the following show up.

Thoughts? Thanks in advance.

2024-12-23 18:36:54.925 WARNING (MainThread) [py.warnings] <string>:1: SyntaxWarning: invalid escape sequence '\s'
2024-12-23 18:36:55.002 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 2912, in async_step_add_device
    user_input = self._validate_data_source_selections(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 3293, in _validate_data_source_selections
    ui_apple_acct      = user_input[CONF_APPLE_ACCOUNT]
                         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'apple_account'

**Comment by gcobb321** [comment]
Hmmm. 
1. I’d like to see your log file. Email the _icloud3.log_ file to geekstergary@gmail.com  error is occurring when updating or adding a device. Maybe an internal table of devices is not getting set when adding the Apple acts and then checking the devices.  
2. Then restart HA and see if you get the error again.

**Comment by rain82k** [comment]
I also get this error. If you also want me to send a log, just let me know. Otherwise I'll just wait for an update.

**Comment by gcobb321** [comment]
@rain82k @karlnewick 

This error should be fixed in v3.1.4.1. Let me know if it worked before I issue a new release.

Unzip into the iclo
[icloud3 v3.1.4.1.zip](https://github.com/user-attachments/files/18240023/icloud3.v3.1.4.1.zip)
ud3 directory and restart HA

**Comment by karlnewick** [comment]
@gcobb321 I've managed to add 2 devices with and without the Mobile Client.

Thank You! Happy Holidays!

**Comment by gcobb321** [comment]
Excellent. I’ve done the update and released v3.1.4.1. It contains a few other things than the version I sent you so be sure to do a HACS update

**Comment by karlnewick** [comment]
Done. Thanks you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
