### ISSUE TITLE
Errors in logs.  Way over my head.

### ISSUE THREAD

**Issue by bkr1969** [gcobb321/icloud3#410]
I've suddenly developed a significant memory leak.  In trying to chase down what may be causing it, I found this in the logs (I'm not suggesting it has anything to do with the leak, just seemed serious):
```
This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/icloud3_main.py:1339
integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 09:00:00 (5 occurrences)
Last logged: 13:00:00

Non-thread-safe operation invoked on an event loop other than the current one
Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 243, in _polling_loop_5_sec_device
    self._main_5sec_loop_special_time_control()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/icloud3/icloud3_main.py", line 613, in _main_5sec_loop_special_time_control
    self._timer_tasks_every_hour()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/icloud3/icloud3_main.py", line 1339, in _timer_tasks_every_hour
    Gb.hass.loop.create_task(hacs_ic3.check_hacs_icloud3_update_available())
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 469, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 831, in call_soon
    self._check_thread()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 868, in _check_thread
    raise RuntimeError(
        "Non-thread-safe operation invoked on an event loop other "
        "than the current one")
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by gcobb321** [comment]
The routine being run is launching a process to see if there is a new iCloud3 version available by checking the version number in HACS. It looks like you got that error 5 times. This is interesting because it runs every hour. 

I have never seen this error on my system but have made a change in the way it is launched in the next release.

**Comment by gcobb321** [comment]
Fixed in v3.1.4.4
