### ISSUE TITLE
2.2.0rc7

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#49]
2020-06-25 01:48:30 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=56FD8396-B62B-11EA-ABD5-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3a242df10>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3a242df10>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=56FD8396-B62B-11EA-ABD5-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3a242df10>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2585, in _refresh_pyicloud_devices_location_data
    api_devices = self.api.devices
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 369, in devices
    service_root, self.session, self.params, self.with_family
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 424, in __init__
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 441, in refresh_client
    "deviceListVersion": 1,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 80, in request
    response = super(PyiCloudSession, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=56FD8396-B62B-11EA-ABD5-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3a242df10>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by gcobb321** [comment]
All of the error messages look like there are problems connecting to iCloud Web Services (Errno:-3, ConnectError, New Connection Error, etc). If there is any error trapping that can be done, all it would do is catch the error and tell you about it. It would not be able to fix it and the result would be the same but with prettier error messages.

A few questions though:
- Does this happen all the time or just occasionally?
- Have you ever had anything working? iCloud3?, iCloud?
- Have you had this issue with both the Find-my-Friends (fmf) and Family Sharing (FamShr) tracking methods?
- Do you have any other issues locating with your phone? (FindMe, FmF)

**Comment by a120578270** [comment]
> All of the error messages look like there are problems connecting to iCloud Web Services (Errno:-3, ConnectError, New Connection Error, etc). If there is any error trapping that can be done, all it would do is catch the error and tell you about it. It would not be able to fix it and the result would be the same but with prettier error messages.
> 
> A few questions though:
> 
> * Does this happen all the time or just occasionally?
> * Have you ever had anything working? iCloud3?, iCloud?
> * Have you had this issue with both the Find-my-Friends (fmf) and Family Sharing (FamShr) tracking methods?
> * Do you have any other issues locating with your phone? (FindMe, FmF)

2.2.0 RC7 seems to happen all the time. I tried it twice. After this problem, icloud3 location would not be refreshed again. The account of my Icloud3 login did not have any equipment, and the equipment was Shared by other accounts in FamSHR. This account was specially used for logging in icloud3, so it seemed that every time an error would be reported to show that there was no one under the account

**Comment by gcobb321** [comment]
I would suggest reviewing the account, the devices/accounts showing in the family sharing list on the account and making sure the devices can be found on the FindMe app.
