### ISSUE TITLE
Error in lost_iphone service

### ISSUE THREAD

**Issue by starostin** [gcobb321/icloud3#56]
I have tried to call lost iphone service. And got an error:
```
2019-07-28 08:28:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139650920177744] 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1174, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/device_tracker.py", line 551, in service_callback_lost_iphone
    group, devicename)
  File "/config/custom_components/icloud3/device_tracker.py", line 6128, in service_handler_lost_iphone
    device = self.tracked_devices.get(arg_devicename)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by gcobb321** [comment]
What version of iCloud3 are you using? If you are using the beta version, the fmf tracking method does not support the lost phone service call. But in any case, the “tracked_devices” field in the last statement says there are no devices being tracked. Look at the device_tracker attributes. The devices being tracked is at the end.

**Comment by starostin** [comment]
I am using last beta version. And tracking method - fmphn. My device is tracking correctly, and I see coordinates and other attributes. But when I try to call lost_iphone service I got this error

**Comment by gcobb321** [comment]
Fixed in next beta, which will probably be the release candidate.
