### ISSUE TITLE
Error when iPhone is not trackable

### ISSUE THREAD

**Issue by nicx** [gcobb321/icloud3#58]
Hey, I am using the latest beta and I get an error each 15 seconds when a tracked iPhone is not trackable. Here is my log:

```
2019-08-13 23:41:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:41:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:41:31 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:41:45 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:41:45 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:41:45 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:42:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:42:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:42:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:42:15 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:42:15 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:42:15 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:42:30 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:42:30 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:42:30 ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:42:45 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:42:45 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:42:45 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:43:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:43:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:43:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:43:15 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:43:15 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:43:15 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:43:30 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:43:30 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:43:30 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:43:45 ERROR (SyncWorker_16) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:43:45 ERROR (SyncWorker_16) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:43:45 ERROR (SyncWorker_16) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:44:00 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:44:00 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:44:00 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:44:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:44:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:44:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:44:30 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:44:30 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:44:30 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:44:45 ERROR (SyncWorker_8) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:44:45 ERROR (SyncWorker_8) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:44:45 ERROR (SyncWorker_8) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:45:00 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:45:00 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:45:00 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:45:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:45:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:45:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:45:30 ERROR (SyncWorker_10) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:45:30 ERROR (SyncWorker_10) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:45:30 ERROR (SyncWorker_10) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:45:45 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:45:45 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:45:45 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:46:00 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:46:00 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:46:00 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:46:15 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:46:15 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:46:15 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:46:30 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:46:30 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:46:30 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:46:45 ERROR (SyncWorker_14) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:46:45 ERROR (SyncWorker_14) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:46:45 ERROR (SyncWorker_14) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:47:00 ERROR (SyncWorker_19) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:47:00 ERROR (SyncWorker_19) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:47:00 ERROR (SyncWorker_19) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:47:15 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:47:15 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:47:15 ERROR (SyncWorker_4) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:47:30 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:47:30 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:47:30 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:47:45 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:47:45 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:47:45 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:48:00 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:48:00 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:48:00 ERROR (SyncWorker_12) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:48:15 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:48:15 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:48:15 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:48:30 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:48:30 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:48:30 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:48:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:48:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:48:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:49:00 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:49:00 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:49:00 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:49:15 ERROR (SyncWorker_14) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:49:15 ERROR (SyncWorker_14) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:49:15 ERROR (SyncWorker_14) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:49:30 ERROR (SyncWorker_19) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:49:30 ERROR (SyncWorker_19) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:49:30 ERROR (SyncWorker_19) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:49:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:49:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:49:45 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:50:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:50:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:50:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:50:15 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:50:15 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:50:15 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:50:30 ERROR (SyncWorker_8) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:50:30 ERROR (SyncWorker_8) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:50:30 ERROR (SyncWorker_8) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:50:45 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:50:45 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:50:45 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:51:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:51:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:51:00 ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:51:15 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:51:15 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:51:15 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:51:30 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:51:30 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:51:30 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:51:45 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:51:45 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:51:45 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:52:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:52:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:52:00 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:52:15 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:52:15 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:52:15 ERROR (SyncWorker_15) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:52:30 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:52:30 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:52:30 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2
2019-08-13 23:52:45 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2237, in _setup_data_fmf
    if 'batteryStatus' in location:
TypeError: argument of type 'NoneType' is not iterable
2019-08-13 23:52:45 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] iCloud Location Data Error
2019-08-13 23:52:45 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] Error, no location data for user1_icloud:iphoneuser2

```

**Comment by nicx** [comment]
@gcobb321 any news to this? its really annoying and my logfile explodes every few days ;)

**Comment by gcobb321** [comment]
Look for beta 8 today or tomorrow. I've changed the way login errors, data access errors, GPS accuracy errors and old location data are handled. It will now try 4 times on a 15-sec interval. If the error still happens, it will move to a 1-min interval, then to 5, 15 and 30 and stay on a 30 min interval until it reconnects or the error resolves itself. 

I've also cleaned up some other errors and added support for iosapp v2.

**Comment by nicx** [comment]
ok sound good, but I will still get these errors in the logfile every 30min when my iphone is switched off in the night, am I right?

**Comment by gcobb321** [comment]
No

**Comment by gcobb321** [comment]
You may have seen that I updated iC3 to beta 8 earlier today. Let me know if this solves (or doesn't solve) your problem.
