### ISSUE TITLE
Constant icloud authentication and many errors but still working

### ISSUE THREAD

**Issue by MikeTannenbaum** [gcobb321/icloud3#61]
Hey, I'm new to icloud3 and loving it so far but having a few issues I cannot resolve.

1. My iPhone is constantly asking me to approve iCloud logins and then sending me 6 digit auth codes. When I setup iCloud 3 I never got the notification within HA to enter the code, which I found odd, but everything started working properly so I thought nothing of it. Could be that I was running the iCloud integration through HA before ditching that for yours so perhaps it was authorized originally? I don't know, but now need to figure out how to stop these constant (few times per hour) requests for auth.

2. I have lots of errors showing up in HA logs that I'm not familiar with resolving. Details below.
<img width="771" alt="Screen Shot 2020-08-17 at 11 27 45 AM" src="https://user-images.githubusercontent.com/792648/90414034-43b9b800-e07d-11ea-8e52-a6db6ca26354.png">

- Failed to parse response with JSON mimetype
`Source: custom_components/icloud3/pyicloud_ic3.py:1011`

- name '_LOGGER' is not defined
```
Traceback (most recent call last):
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 193, in _raise_error
    self.session.cookies.clear()
AttributeError: 'PyiCloudSession' object has no attribute 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 128, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 199, in _raise_error
    _LOGGER.exception(err)
NameError: name '_LOGGER' is not defined
```

- (450)
`Source: custom_components/icloud3/pyicloud_ic3.py:1011`

- 'str' object has no attribute 'json'
```
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2626, in _get_famshr_data
    status   = device.status(DEVICE_STATUS_SET)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1011, in status
    self.manager.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 936, in refresh_client
    self.response = req.json()
AttributeError: 'NoneType' object has no attribute 'json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2081, in _update_device_icloud
    dev_data = self._get_famshr_data(devicename)
  File "/config/custom_components/icloud3/device_tracker.py", line 2632, in _get_famshr_data
    self.api.authenticate()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 331, in authenticate
    response = req.json()
AttributeError: 'str' object has no attribute 'json'
```

Here's my basic config.yaml
```
device_tracker:
  - platform: icloud3
    username: REDACTED
    password: !secret REDACTED
    tracking_method: famshr
    inzone_interval: '15 min'
    stationary_inzone_interval: '15 min'
    track_devices:
    - mikeysiphone > mike.jpg
    - arielle_siphone > arielle.jpg
```
I'm running HA within a docker container within proxmox, though not sure how that would be affecting any of this.

Would love your help interpreting the errors if you know how — that part of things is beyond my field of knowledge.

Thanks for making such an awesome plugin! Seems like exactly what I needed since I was struggling so hard with iPhone presence tracking.

**Comment by MikeTannenbaum** [comment]
The errors just keep piling up and I'm not sure what I'm doing wrong...

```
Logger: homeassistant.components.websocket_api.http.connection.140541536381632
Source: custom_components/icloud3/device_tracker.py:641
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:14:01 PM (1 occurrences)
Last logged: 2:14:01 PM

'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1347, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/device_tracker.py", line 768, in service_callback_update_icloud
    ICLOUD3_GROUP_OBJS[group].service_handler_icloud_update(
  File "/config/custom_components/icloud3/device_tracker.py", line 7636, in service_handler_icloud_update
    if instr(arg_command, 'event_log') == False:
  File "/config/custom_components/icloud3/device_tracker.py", line 641, in instr
    return string.find(find_string) >= 0
AttributeError: 'NoneType' object has no attribute 'find'
```

```
Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:1420
Integration: icloud3 (documentation)
First occurred: 12:05:35 PM (2198 occurrences)
Last logged: 3:23:50 PM

local variable 'v2_trigger_changed_secs' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1420, in _polling_loop_5_sec_device
    self._secs_to_time(v2_trigger_changed_secs))
UnboundLocalError: local variable 'v2_trigger_changed_secs' referenced before assignment
```

**Comment by gcobb321** [comment]
The iCloud3 v2.1.0 on HACS does not support iCloud 2fa accounts. That is leading to the constant notifications. It may also be leading to the pyicloud_ic3 errors.

v2.2.0 solves all these issues and adds a lot of new functions. I'm still doing the docs for it. I just posted v2.2.0 Release Candidate 11. Go [here](https://community.home-assistant.io/t/icloud3-v2-1-device-tracker-advanced-tracking-features-ios-app-monitoring/148943/552) for more information about it and how to download and install it.

**Comment by MikeTannenbaum** [comment]
Ooooooo I should have checked versioning... good call. I’ll install the latest RC and see how that goes. Do your know if it’s easy to then switch to HACS without losing and config?

**Comment by gcobb321** [comment]
You won’t lose anything going back to hacs
