### ISSUE TITLE
v2.2-rc11b : zone not_set to home although entity state already show home

### ISSUE THREAD

**Issue by dony71** [gcobb321/icloud3#66]
my device tracker config :
```
device_tracker:
  - platform: icloud3
    username: "xxx@gmail.com"
    password: "xxx"
    tracking_method: famshr
    track_devices:
      - iphonexr > /local/dony.jpg
      - iphonese > /local/mariana.jpg
```
no problem on iphonexr, but iphonese zone always not_set
some log file info :
```
2020-08-20 10:09:31 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Decoding > iphonese > /local/mariana.jpg
2020-08-20 10:09:31 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆*◆ Extract Trk_Dev Parm, ic3dev_info-['iphonese', 'iphone', 'Se', '', '/local/mariana.jpg', '', '', ['home']]
```
then
```
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆*◆ ▲---------▲--FAMSHR.ICLOUD.DATA.-.IPHONESE--▲---------▲
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Not Tracking Devices >. • popss_iphone (Pops’s iPhone/iPhone). • dons_mac (Don’s Mac/iMac)
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Tracking Devices >. • iphonexr (iPhoneXR/iPhone). • iphonese (iPhoneSE/iPhone)
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Stage 3 > Identify iOS App entities, Verify tracked devices
```
then
```
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Scanning /home/homeassistant/.homeassistant/.storage/core.entity_registry Entity Registry for iOS App device_tracker iphonese
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆iphonese◆ SCAN ENTITY REG, device_trackers found-[. • iphonese_2 (_2)]
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Matched iOS App sensor.iphonese_last_update_trigger with iCloud3 tracked_device iphonese
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Verified Device > Se (iphonese)
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] iOS App monitoring > Se (iphonese) > . • device_tracker.iphonese_2, . • sensor.iphonese_last_update_trigger
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] iOS App Location Requests > Se (iphonese) > . •
```
then
```
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Tracking Devices > . •  iphonexr ( ... _2). • iphonese ( ... _2)
2020-08-20 10:09:32 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Stage 4 > Configure tracked devices
```
then
```
2020-08-20 10:09:37 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Initialize Data Fields > iphonese
2020-08-20 10:09:37 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆iphonese◆ SETUP BASE KWARGS zone_name-None, inzone-state-True
2020-08-20 10:09:37 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs ___ (_start_icloud3)
2020-08-20 10:09:37 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Last State-not_set, This State-home
2020-08-20 10:09:37 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs-{'gps': (37.49, -121.9206), 'battery': 0, 'gps_accuracy': 0}{'name': 'Se', 'zone': 'not_set', 'last_zone': 'not_set', 'zone_timestamp': '', 'interval': '', 'zone_distance': 0, 'calc_distance': 0, 'waze_distance': 0, 'last_located': '00:00:00', 'last_update': '00:00:00', 'next_update': '00:00:00', 'poll_count': '0:0:0', 'dir_of_travel': '', 'travel_distance': 0, 'trigger': 'iCloud3@00:00:00', 'timestamp': '2020-08-20T17:09:37', 'battery': 0, 'info': '● HA is initializing dev_trk attributes ●', 'vertical_accuracy': 0}
2020-08-20 10:09:38 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] ◆iphonese◆ Set up sensor name for device, devicename-iphonese, entity_base-iphonese
2020-08-20 10:09:38 INFO (SyncWorker_15) [custom_components.icloud3.device_tracker] Initialize Sensors > iphonese
```
then
```
2020-08-20 10:09:57 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) FamShr update started (Next Update Time)
2020-08-20 10:09:57 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ ▼▼▼.FAMSHR.▼▼▼.IPHONESE-GROUP1-HOME.▼▼▼▼▼▼.STATE-HOME.▼▼▼▼▼▼.NEXT.UPDATE.TIME.▼▼▼
2020-08-20 10:09:57 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ = = = Prep Data From FamShr = = = (Now-1597943393)
2020-08-20 10:09:57 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ LOCATION DATA-{'name': '', 'device_class': 'iPhone', 'battery_level': 0, 'battery_status': 'Unknown', 'device_status': '', 'low_power_mode': False, 'timestamp': 0, 'timestamp_time': '00:00:00', 'age': 9999999999, 'latitude': 0.0, 'longitude': 0.0, 'altitude': 0.0, 'isOld': False, 'gps_accuracy': 0, 'vertical_accuracy': 0})
2020-08-20 10:09:57 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] Se (iphone) Sending location request to iCloud > Last Updated: Never (Initial Locate)
```
then
```
2020-08-20 10:09:58 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) Refreshed FamShr iCloud location data
2020-08-20 10:09:58 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ SETUP BASE KWARGS zone_name-None, inzone-state-True
2020-08-20 10:09:58 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs ___ (DetIntlErrorRetry)
2020-08-20 10:09:58 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Last State-not_set, This State-home
2020-08-20 10:09:58 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs-{'gps': (37.49, -121.9206), 'battery': 0, 'gps_accuracy': 0}{'last_update': '10:09:53', 'interval': '15 sec', 'next_update': '10:10:15', 'poll_count': '0:0:1', 'info': '●● No Location Coordinates, (0.0, 0.0) ●●', 'timestamp': '2020-08-20 10:09:58', 'name': 'Se', 'trigger': 'iCloud3@00:00:00'}
2020-08-20 10:09:59 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ ▲▲▲.FAMSHR.▲▲▲.IPHONESE-GROUP1-HOME.▲▲▲▲▲▲.STATE-HOME.▲▲▲▲▲▲.NEXT.UPDATE.TIME.▲▲▲
```
then
```
2020-08-20 10:10:02 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] State Change detected for iphonese > not_set to home
```
then
```
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) FamShr update started (State Change/Resume)
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ ▼▼▼.FAMSHR.▼▼▼.IPHONESE-GROUP1-HOME.▼▼▼▼▼▼.STATE-HOME.▼▼▼▼▼▼.STATE.CHANGE/RESUME.▼▼▼
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ = = = Prep Data From FamShr = = = (Now-1597943393)
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ LOCATION DATA-{'name': '', 'device_class': 'iPhone', 'battery_level': 0, 'battery_status': 'Unknown', 'device_status': '', 'low_power_mode': False, 'timestamp': 0, 'timestamp_time': '00:00:00', 'age': 9999999999, 'latitude': 0.0, 'longitude': 0.0, 'altitude': 0.0, 'isOld': False, 'gps_accuracy': 0, 'vertical_accuracy': 0})
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] Se (iphone) Sending location request to iCloud > Last Updated: Never (Initial Locate)
```
then
```
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) Refreshed FamShr iCloud location data
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ SETUP BASE KWARGS zone_name-None, inzone-state-True
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs ___ (DetIntlErrorRetry)
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Last State-not_set, This State-home
2020-08-20 10:10:07 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs-{'gps': (37.49, -121.9206), 'battery': 0, 'gps_accuracy': 0}{'last_update': '10:09:53', 'interval': '15 sec', 'next_update': '10:10:15', 'poll_count': '0:0:2', 'info': '●● No Location Coordinates, (0.0, 0.0) ●●', 'timestamp': '2020-08-20 10:10:07', 'name': 'Se', 'trigger': 'iCloud3@00:00:00'}
2020-08-20 10:10:08 INFO (SyncWorker_33) [custom_components.icloud3.device_tracker] ◆iphonese◆ ▲▲▲.FAMSHR.▲▲▲.IPHONESE-GROUP1-HOME.▲▲▲▲▲▲.STATE-HOME.▲▲▲▲▲▲.STATE.CHANGE/RESUME.▲▲▲
```
then
```
2020-08-20 10:10:20 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) FamShr update started (Next Update Time)
2020-08-20 10:10:20 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ ▼▼▼.FAMSHR.▼▼▼.IPHONESE-GROUP1-HOME.▼▼▼▼▼▼.STATE-HOME.▼▼▼▼▼▼.NEXT.UPDATE.TIME.▼▼▼
2020-08-20 10:10:20 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ = = = Prep Data From FamShr = = = (Now-1597943415)
2020-08-20 10:10:20 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ LOCATION DATA-{'name': '', 'device_class': 'iPhone', 'battery_level': 0, 'battery_status': 'Unknown', 'device_status': '', 'low_power_mode': False, 'timestamp': 0, 'timestamp_time': '00:00:00', 'age': 9999999999, 'latitude': 0.0, 'longitude': 0.0, 'altitude': 0.0, 'isOld': False, 'gps_accuracy': 0, 'vertical_accuracy': 0})
2020-08-20 10:10:20 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] Se (iphone) Sending location request to iCloud > Last Updated: Never (Initial Locate)
```
then
```
2020-08-20 10:10:21 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) Refreshed FamShr iCloud location data
2020-08-20 10:10:21 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ SETUP BASE KWARGS zone_name-None, inzone-state-True
2020-08-20 10:10:21 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs ___ (DetIntlErrorRetry)
2020-08-20 10:10:21 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Last State-not_set, This State-home
2020-08-20 10:10:21 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs-{'gps': (37.49, -121.9206), 'battery': 0, 'gps_accuracy': 0}{'last_update': '10:10:15', 'interval': '15 sec', 'next_update': '10:10:30', 'poll_count': '0:0:3', 'info': '●● No Location Coordinates, (0.0, 0.0) ●●', 'timestamp': '2020-08-20 10:10:21', 'name': 'Se', 'trigger': 'iCloud3@00:00:00'}
2020-08-20 10:10:22 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] ◆iphonese◆ ▲▲▲.FAMSHR.▲▲▲.IPHONESE-GROUP1-HOME.▲▲▲▲▲▲.STATE-HOME.▲▲▲▲▲▲.NEXT.UPDATE.TIME.▲▲▲
2020-08-20 10:10:22 INFO (SyncWorker_61) [custom_components.icloud3.device_tracker] State Change detected for iphonese > not_set to home
```

**Comment by dony71** [comment]
I notice there is ERROR, but not sure whether this ERROR belong to iphonese?
```
2020-08-20 10:18:17 INFO (SyncWorker_22) [custom_components.icloud3.device_tracker] ◆iphonese◆ Se (iphone) Refreshed FamShr iCloud location data
2020-08-20 10:18:17 INFO (SyncWorker_22) [custom_components.icloud3.device_tracker] ◆iphonese◆ SETUP BASE KWARGS zone_name-None, inzone-state-True
2020-08-20 10:18:17 INFO (SyncWorker_22) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs ___ (DetIntlErrorRetry)
2020-08-20 10:18:17 INFO (SyncWorker_22) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Last State-not_set, This State-home
2020-08-20 10:18:17 INFO (SyncWorker_22) [custom_components.icloud3.device_tracker] ◆iphonese◆ WRITE Attrs-{'gps': (37.49, -121.9206), 'battery': 0, 'gps_accuracy': 0}{'last_update': '10:18:15', 'interval': '15 sec', 'next_update': '10:18:30', 'poll_count': '0:0:63', 'info': '●● No Location Coordinates, (0.0, 0.0) ●●', 'timestamp': '2020-08-20 10:18:17', 'name': 'Se', 'trigger': 'iCloud3@00:00:00'}
2020-08-20 10:18:17 ERROR (SyncWorker_22) [custom_components.icloud3.device_tracker] local variable 'gps_accuracy' referenced before assignment
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/device_tracker.py", line 2522, in _update_device_icloud
    event_msg = (f"Discarding > {info_msg} > GPS-{format_gps(latitude, longitude, gps_accuracy)}, "
UnboundLocalError: local variable 'gps_accuracy' referenced before assignment
2020-08-20 10:18:17 ERROR (SyncWorker_22) [custom_components.icloud3.device_tracker] ►INTERNAL ERROR-RETRYING (_update_device_icloud:OverallUpdate-local variable 'gps_accuracy' referenced before assignment)
```

**Comment by dony71** [comment]
attributes device_tracker.iphonese under developer tools > states
```
source_type: gps
latitude: 37.49
longitude: -121.9206
gps_accuracy: 0
scanner: AsusWrtDeviceScanner
name: Se
zone: not_set
last_zone: not_set
zone_timestamp: 
interval: 15 sec
travel_time: 
zone_distance: 0
calc_distance: 0
waze_distance: 0
last_located: 00:00:00
last_update: 5:19:00
next_update: 5:19:15
poll_count: 0:0:400
dir_of_travel: 
travel_distance: 0
trigger: iCloud3@00:00:00
timestamp: 2020-08-20 17:19:04
authenticated: 
battery: 0
battery_status: 
info: ●● No Location Coordinates, (0.0, 0.0) ●●
altitude: 0
vertical_accuracy: 0
device_status: 
low_power_mode: 
group: group1
entity_picture: /local/mariana.jpg
tracking:  iphonexr ( ... _2), iphonese ( ... _2) (FamShr)
icloud3_version: 2.2.0rc11b
ip: 10.168.1.79
friendly_name: IPHONESE
icon: mdi:cellphone-basic
```
I notice blank on authenticated
Any idea why?

**Comment by gcobb321** [comment]
I think it's an iCloud authentication/verification code issue that needs to be done before the fmf & famshr devices can be set up. I've uploaded Release Candidate 11c zip file to the Release Candidate directory  that has code that I think may correct the problem. It should respond to the Verification Request when iCloud3 starts. It will put some info in the Event Log that it is needed and use the iOS App tracking method until it has been done. After successfully completing the verification, it will reset to use fmf or famshr.

I have had some problems where the Trusted Device ID selection and Verification Code Entry forms would not go away. This was caused by the selected item being rejected by Apple because it was incorrect even though it was OK. That may be some type of other error or I just banged on Apple to many times in a short period of time. Restarting HA seems to help sometimes but not always. It seems like it starts when I enter an invalid code to try to display an Invalid Code Entered error msg.

Let me know if it works or doesn't work. Thanks

Download the icloud3-v2.2.0-rc11c.zip [here](https://github.com/gcobb321/icloud3/tree/master/v2.2.0-Release%20Candidate).

**Comment by dony71** [comment]
icloud3-v2.2.0-rc11c.zip has same problem, no authentication shows.
I try roll back to v2.1. With this version, no authentication also shows, but sensor.iphonese_badge being set to home instead of not_set in v2.2
I notice there is Initializing info after set  Tracking (FamShr) in log file below
```
2020-08-20 14:48:22 INFO (SyncWorker_25) [custom_components.icloud3.device_tracker] None(None) iCloud Account devices, iphonexr(OK), popssiphone(Not Tracked), donsmac(Not Tracked), iphonese(OK)
2020-08-20 14:48:22 INFO (SyncWorker_25) [custom_components.icloud3.device_tracker] Se(iphone) Tracking (FamShr) > iphonese(Se)
2020-08-20 14:48:22 INFO (SyncWorker_25) [custom_components.icloud3.device_tracker] Se(iphone) IOS App v2 monitoring > device_tracker.iphonese_2, sensor.iphonese_last_update_trigger
2020-08-20 14:48:22 INFO (SyncWorker_25) [custom_components.icloud3.device_tracker] None(None) Tracking Devices >  iphonexr(iphonexr_2), iphonese(iphonese_2)
2020-08-20 14:48:25 INFO (SyncWorker_25) [custom_components.icloud3.device_tracker] Se(iphone) Initializing v2.1 > Stage 4, Set up iphonese
2020-08-20 14:48:25 INFO (SyncWorker_25) [custom_components.icloud3.device_tracker] Se(iphone) Set Stationary Zone > iphonese_stationary, GPS-(37.49492, -121.9206), DistFromLastLoc-0m
2020-08-20 14:48:35 ERROR (SyncWorker_63) [custom_components.icloud3.device_tracker] Se(iphone) iCloud3 Error: IOS App v2 Entity device_tracker.iphonese_2 does not contain location attributes (latitude, longitude). Refresh & restart IOS App on device, request a Manual Refresh, check Developer Tools>States entity for location attributes, check HA integrations for the entity. Restart HA or issue 'device_tracker.icloud3_reset' Service Call. Reverting to IOS App v1.
2020-08-20 14:48:43 ERROR (SyncWorker_33) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/device_tracker.py", line 4379, in _trace_device_attributes
    if ATTR_LOCATION in attrs:
TypeError: argument of type 'NoneType' is not iterable
2020-08-20 14:48:43 ERROR (SyncWorker_33) [custom_components.icloud3.device_tracker] local variable 'loc_time_secs' referenced before assignment
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/device_tracker.py", line 2709, in _get_famshr_data
    location_isold_flag, loc_time_secs, altitude,
UnboundLocalError: local variable 'loc_time_secs' referenced before assignment
2020-08-20 14:48:43 ERROR (SyncWorker_33) [custom_components.icloud3.device_tracker] None(None) iCloud3 Error: An error occurred accessing the iCloud account xxx@gmail.com for iphonese. This can be an account authentication issue or no location data is available. Retrying at next update time. Retry #3
2020-08-20 14:49:04 ERROR (SyncWorker_44) [custom_components.icloud3.device_tracker] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/device_tracker.py", line 4379, in _trace_device_attributes
    if ATTR_LOCATION in attrs:
TypeError: argument of type 'NoneType' is not iterable
2020-08-20 14:49:04 ERROR (SyncWorker_44) [custom_components.icloud3.device_tracker] local variable 'loc_time_secs' referenced before assignment
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/device_tracker.py", line 2709, in _get_famshr_data
    location_isold_flag, loc_time_secs, altitude,
UnboundLocalError: local variable 'loc_time_secs' referenced before assignment
2020-08-20 14:49:05 INFO (SyncWorker_44) [custom_components.icloud3.device_tracker] Se(iphone) State Change Detected for iphonese > not_set to home
```

**Comment by gcobb321** [comment]
I’ll look at the error message in a while. The authentication is controlled by the cookie file in the ‘config/.storage/icloud’ directory. The file is your email without any punctuation. Rename that file and then restart HA and see if you get the authentication/verification request in the HA Notification sidebar. Don’t delete it in case you have to rename it back.

**Comment by dony71** [comment]
yes, this resolves the issues
maybe somehow authentication corrupted ?
thank you for your support
