### ISSUE TITLE
Error in the Log file

### ISSUE THREAD

**Issue by naseemr** [gcobb321/icloud3#70]
After the 99.3 upgrade I am seeing the following error.
2019-10-09 11:22:14 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtStatZone-Invalid entity id encountered: zone._stationary. Format should be <domain>.<object_id>)
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>)
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._zone. Format should be <domain>.<object_id>
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor._zone. Format should be <domain>.<object_id>)
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] local variable 'state' referenced before assignment
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] local variable 'state' referenced before assignment
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._info. Format should be <domain>.<object_id>
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor._info. Format should be <domain>.<object_id>)
2019-10-09 11:22:23 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] local variable 'state' referenced before assignment
2019-10-09 11:22:24 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] local variable 'state' referenced before assignment
2019-10-09 11:22:24 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] local variable 'state' referenced before assignment
2019-10-09 11:22:24 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>
2019-10-09 11:22:24 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>)
2019-10-09 11:22:24 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._zone. Format should be <domain>.<object_id>
2019-10-09 11:22:24 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor._zone. Format should be <domain>.<object_id>)

**Comment by gcobb321** [comment]
The format of the sensor item is 'sensor.<devicename>_attribute. So tht indicates something is wrong with the devicename of the device being tracked.

I just upgraded to 0.99.3 without any issues. But I'm running the iCloud3 2.0 release candidate that has additional error checking and may handle things differently then the version you are running.

What version of iCloud3 are you running? 
Did it work before? 
What does your device_tracker config parms look like? 
Have you looked at the HA log file for any errors related to iCloud3? It should show the devices being tracked.
Are sensors being created for any devices you are tracking or is nothing being created?

**Comment by naseemr** [comment]
HA log file extract:
2019-10-10 22:18:31 INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 3, Setting up naseemr_icloud/naseemiphonexs
2019-10-10 22:18:31 INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] naseemiphonexs(iphone) Created Stationary Zone, GPS=(90, 180)
2019-10-10 22:18:32 INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 3, Setting up naseemr_icloud/
2019-10-10 22:18:32 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtStatZone-Invalid entity id encountered: zone._stationary. Format should be <domain>.<object_id>)
2019-10-10 22:18:33 INFO (MainThread) [homeassistant.components.kodi.media_player] Unable to fetch kodi data
2019-10-10 22:18:37 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform onkyo is taking over 10 seconds.
2019-10-10 22:18:41 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line 3731, in _update_device_sensors
    self.hass.states.set(sensor_entity, value, sensor_attr)
  File "/home/pi/.local/lib/python3.7/site-packages/homeassistant/core.py", line 946, in set
    context,
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/pi/.local/lib/python3.7/site-packages/homeassistant/util/async_.py", line 208, in run_callback
    future.set_result(callback(*args))
  File "/home/pi/.local/lib/python3.7/site-packages/homeassistant/core.py", line 986, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/home/pi/.local/lib/python3.7/site-packages/homeassistant/core.py", line 723, in __init__
    ).format(entity_id)
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>
2019-10-10 22:18:41 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor._battery. Format should be <domain>.<object_id>)
2019-10-10 22:18:41 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] Invalid entity id encountered: sensor._zone. Format should be <domain>.<object_id>
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line 3731, in _update_device_sensors

**Comment by gcobb321** [comment]
I used your devicename and it work fine on my system using my fmf account. From one of the log messages dissplaying the data, it looked like you are running a very old version of the beta (beta 3?). The latest was beta 8. I just put the v2.0rc (release candidate) on the iCloud3 repository in the beta folder but without any change documentation. I'm wrapping up the documentation (in a different repository and still a work-in-process) and still have to add that. Use the links below.

Download v2.0rc [here](https://github.com/gcobb321/icloud3/tree/master/beta)
Review the iCloud3 documenentation [here](https://gcobb321.github.io/icloud3_docs/#)

Try it out and let me know if you are still having problems. At that time, I may want you to send some files to me via email for review.

**Comment by naseemr** [comment]
Thank you for spending time on my issue. I know you are very busy. I n the
beta directory, I am missing init.py files.
is it missing or I need to get it from old version?
Thanks,

**Comment by naseemr** [comment]
Hi Gary,
I updated the icloud3 and still having issues.
Below is the log.

2019-10-11 22:59:53 INFO (SyncWorker_0)
[custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization >
Stage 2, Setting up tracked devices 2019-10-11 22:59:53 ERROR
(SyncWorker_0) [custom_components.icloud3.device_tracker] [Errno 2] No such
file or directory: '/config/.storage/core.entity_registry' Traceback (most
recent call last): File
"/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line
5341, in _get_entity_registry_entities entitity_reg_file =
open('/config/.storage/core.entity_registry') FileNotFoundError: [Errno 2]
No such file or directory: '/config/.storage/core.entity_registry'
2019-10-11 22:59:53 ERROR (SyncWorker_0)
[custom_components.icloud3.device_tracker] local variable 'parameters'
referenced before assignment Traceback (most recent call last): File
"/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line
5262, in _setup_track_device_config_parm_decode items =
parameters.split(',') UnboundLocalError: local variable 'parameters'
referenced before assignment 2019-10-11 22:59:53 ERROR (SyncWorker_0)
[custom_components.icloud3.device_tracker] local variable 'device_info'
referenced before assignment Traceback (most recent call last): File
"/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line
5144, in _setup_tracked_devices_config_parm track_device_line,
iosapp_v2_entities) File
"/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line
5331, in _setup_track_device_config_parm_decode return device_info
UnboundLocalError: local variable 'device_info' referenced before
assignment 2019-10-11 22:59:55 ERROR (SyncWorker_0)
[custom_components.icloud3.device_tracker] Error: iCloud3 setup aborted for
group 'group1', no devices to track 2019-10-11 22:59:55 INFO (MainThread)
[homeassistant.setup] Setup of domain device_tracker took 8.5 seconds.
2019-10-11 22:59:55 INFO (MainThread) [homeassistant.setup] Setting up ios
2019-10-11 22:59:55 INFO (MainThread) [homeassistant.setup] Setup of domain
ios took 0.0 seconds. 2019-10-11 22:59:55 INFO (MainThread)
[homeassistant.components.sensor] Setting up sensor.ios 2019-10-11 22:59:55
INFO (SyncWorker_11) [homeassistant.loader] Loaded notify from
homeassistant.components.notify 2019-10-11 22:59:55 INFO (MainThread)
[homeassistant.setup] Setting up notify 2019-10-11 22:59:55 INFO
(MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds.
2019-10-11 22:59:55 INFO (MainThread) [homeassistant.components.notify]
Setting up notify.ios

**Comment by gcobb321** [comment]
Thanks for trying v2.0rc. Thought I had all the bugs fixed but will fix this one tomorrow and let you know when it’s available.

 What version of Home Assistant are you using? What version of HA IOS app do you have?

**Comment by naseemr** [comment]
Gary,
My HA is 99.3 and iOS 13 HA app.
Thanks,
Naseem

**Comment by gcobb321** [comment]
I’m also running HA .99.3. I was interested in the IOS app Version, not the version of IOS from Apple. I’m running IOS app version v2.0beta62 on one phone and v1.51 on another. 

The reason I asked, HA stores entity information for mobile apps in the entity registry. On my set up, the file used is '/config/.storage/core.entity_registry’. Do you have that file? In that directory? Or is it somewhere else? If you’re running IOS app v1.51, it might not exist, which is ok and it was suppose to assume v1.51 if it didn’t without crashing. If you’d running v2.0beta, I need to know since that is how I determine the device tracker name associated with the phone.

**Comment by naseemr** [comment]
Hi Gary,
My HA ios app version is 1.5.1.
I also have .storage/core_entity_registry file in config directory.
Again, thanks so much for helping me with this.

**Comment by gcobb321** [comment]
I just uploaded a new version (v2.0rc-a) that I think takes care of the problem (actually 2 problems). It's ready now so give it a go. If it works, let me know (and also any other issues you otice) since you are the first person, other than myself, to use it.

Thanks.

BTW-I am looking for '/config/.storage/core.entity_registry'. You said you have ' .storage/core_entity_registry'. You put an underline ('_') between 'core' and 'registry' where I have a period ('.)'. Can you verify that it is not a typo?

Another question-Where are you located?

Gary

**Comment by naseemr** [comment]
Gary,
It was a typo. I see core.entity_registry.  I am traveling, I will try as
soon as I can.
Best regards,

**Comment by naseemr** [comment]
Gary good news! All the errors are gone! I am all good now. One thing I
don’t see is my son’s device. Is there some new config Parm I need?

Thanks again for your help.
Take care,
Naseem

**Comment by gcobb321** [comment]
Could be lots of things. Find my friends setting, track_devices parameter,iCloud account you are using. Etc. 

Set up iCloud3 Event Log custom card and see status of devices during startup. 
Review the iCloud3 documenentation here

**Comment by naseemr** [comment]
Gary,
Something changed in this beta? Getting error for included-device_type.
My config is:

device_tracker:
  - platform: icloud3
    username: !secret icloudusername
    password: !secret icloudpass
    include_device_type: iphone


Sun Oct 13 2019 06:26:46 GMT-0600 (MDT)

Invalid config for [device_tracker.iclod3]: [include_device_type] is
an invalid option for [device_tracker.icloud3]. Check:
device_tracker.icloud3->include_device_type. (See
/home/pi/.homeassistant/configuration.yaml, line 55). Please check the
docs at https://home-assistant.io/components/device_tracker.icloud3/

**Comment by gcobb321** [comment]
A lot of things changed in the latest release on how devices to be tracked are specified in the config file. One was the include _devices was replaced by track _devices. This was to support other tracking methods including Find-my-Friends that get around the constant login notifications in 2fa accounts.

You really need to go back through the change log in the beta directory and read the documentation I have referred to several times above to see how devices are now tracked. There is a lot of things you will miss out on if you don’t.

**Comment by naseemr** [comment]
Gary,
Read the new changes and updated the method to fmphn. That gave my son’s
phone . But I am seeing the following error log.


Mon Oct 14 2019 14:06:00 GMT-0600 (MDT)

'PyiCloudSession' object has no attribute 'session'

Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py",
line 111, in request
    self._raise_error(response.status_code, response.reason)
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py",
line 174, in _raise_error
    self.session.cookies.clear()
AttributeError: 'PyiCloudSession' object has no attribute 'session'

Everything else works fine.

**Comment by gcobb321** [comment]
I just put an error check in that routine to not crash pyicloud_ic3py. I have no idea if it will work but give it a go. Download pyicloud_ic3.py from the beta directory.

The stuff I did in the original pyicloud.py program was to get it to support find my Friends location services by using code others wrote without really understanding what was going on.

I can't remember if I checked FmPhn out again after Apple released iOS 13 so you might get some type of error not related to iCloud3.

Let me know what happens. BTW where do you live. Just curious as to what part of the world users of iCloud3 are from.


————————
Gary Cobb

**Comment by gcobb321** [comment]
Also. Just to let you know, I updated pyicloud_ic3.py on GitHub using my iPad so I haven't tried to restart Home Assistant with the changes. I think I typed everything correctly but you never know.

————————
Gary Cobb

**Comment by naseemr** [comment]
Gary,
I replaced the file with your new one. So far I don’t see tang error.
Hopefully this is going to work. Will monitor and let you know.
I am in Dallas, Texas.
Thanks.

**Comment by naseemr** [comment]
Hi gary,
I am seeing the following error now.
2019-10-15 18:22:15 ERROR (SyncWorker_19)
[custom_components.icloud3.pyicloud_ic3.http] can only concatenate str (not
"int") to str
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py",
line 111, in request
    self._raise_error(response.status_code, response.reason)
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py",
line 179, in _raise_error
    return "Error=" + code, reason
TypeError: can only concatenate str (not "int") to str
2019-10-15 18:22:15 WARNING (SyncWorker_19)
[custom_components.icloud3.pyicloud_ic3.http] Failed to parse response with
JSON mimetype
2019-10-15 18:22:15 INFO (SyncWorker_19)
[custom_components.icloud3.pyicloud_ic3] Authenticating as
naseemra@gmail.com
2019-10-15 18:22:17 INFO (SyncWorker_19)
[custom_components.icloud3.pyicloud_ic3] Authentication completed
successfully

2019-10-15 18:44:00 ERROR (SyncWorker_7)
[custom_components.icloud3.pyicloud_ic3.http] can only concatenate str (not
"int") to str
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py",
line 111, in request
    self._raise_error(response.status_code, response.reason)
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py",
line 179, in _raise_error
    return "Error=" + code, reason
TypeError: can only concatenate str (not "int") to str
2019-10-15 18:44:00 WARNING (SyncWorker_7)
[custom_components.icloud3.pyicloud_ic3.http] Failed to parse response with
JSON mimetype
2019-10-15 18:44:00 INFO (SyncWorker_7)
[custom_components.icloud3.pyicloud_ic3] Authenticating as
naseemra@gmail.com
2019-10-15 18:44:04 INFO (SyncWorker_7)
[custom_components.icloud3.pyicloud_ic3] Authentication completed
successfully
2019-10-15 18:44:04 INFO (SyncWorker_7)
[custom_components.icloud3.device_tracker] Reauthenticated FmPhn account
naseemra@gmail.com for naseemiphonexs

**Comment by naseemr** [comment]
Gary,
for Find My Friends, what ios App do I install? I think Find my Phone the
app keep asking permission.
Thanks,

**Comment by gcobb321** [comment]
Yes, using an account with 2fa keeps asking for permissions. That is why I added the fmf tracking method.

Earlier this summer, in ios12, you would use the Find My Friends app. IOS13 consolidated the Find my Friends and Find My Phone into a single app -- Find My. I kept the same terminology but if it confusing, maybe I should change it now that there is only one app.

Basically, fmf uses a non-2fa account while fmphn uses a 2fa account. The docs explain the differences and how to set up a second non-2fa account. It is best to not set it up using an app (that will force you to enable 2fa on the new account) but to use a computer that will let you set up a non-2fa account.

The docs are back up and pretty well finalized. Go to the [documentation here](https://gcobb321.github.io/icloud3_docs/#/) and look at the Setting up Your iCloud Account chapter.

I'll check out the new pyicloud3_ic3 error message. I wonder if the constant reauthorizations is what is causing the errors you are seeing.

Gary

**Comment by gcobb321** [comment]
I just added some more error checking to the pyicloud_ic3.py program to catch the error you just sent me a few minutes ago. It's available [here](https://github.com/gcobb321/icloud3/tree/master/beta).

**Comment by naseemr** [comment]
Gary,
I downloaded the new file. But this time I used fmf ( non-2fa) method, Iam seeing the following error.
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.pyicloud_ic3]        Authentication completed successfully
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] Authentication for User: naseem75023@gmail.com (group1) successful
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] iCloud3 v2.0rc-a Initalization > Stage 2, Setting up tracked devices
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] Decoding track_devices <naseemiphonexs > naseemra@gmail.com>
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] Decoding track_devices <Yee > samienra@gmail.com>
2019-10-16 18:31:23 ERROR (SyncWorker_2) [custom_components.icloud3.device_track       er] 'fmf'
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", li       ne 5008, in _setup_tracked_devices_for_fmf
    fmf = self.api.friends
  File "/home/pi/.homeassistant/custom_components/icloud3/pyicloud_ic3.py", line        459, in friends
    service_root = self.webservices['fmf']['url']
KeyError: 'fmf'
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] Not Tracking (FmF) > naseemiphonexs (naseemra@gmail.com)
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] IOS App v1 monitoring > device_tracker.naseemiphonexs
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] Not Tracking (FmF) > yee (samienra@gmail.com)
2019-10-16 18:31:23 INFO (SyncWorker_2) [custom_components.icloud3.device_tracke       r] IOS App v1 monitoring > device_tracker.yee
2019-10-16 18:31:23 ERROR (SyncWorker_2) [custom_components.icloud3.device_track       er] Error: iCloud3 setup aborted for group 'group1', no devices to track

**Comment by gcobb321** [comment]
Are you using a non-2fa account in the username parameter? Did you add the devices to follow in the contacts list for that account? Can you see them in the Find Me app? What do your device_tracker configuration parms look like? Does it have the email address of the accounts (friends) you are tracking? Let me see your config file  to see how you have set up iCloud3.

**Comment by naseemr** [comment]
Apology for late response Yes, I am using new account that I created and  used in my Mac. But forgot to do share location with new account. Now I am able to see the location in Mac too. 
![fmf](https://user-images.githubusercontent.com/3306597/67027019-78ac5580-f0ce-11e9-96f1-a95d94566fff.JPG)
![state_device](https://user-images.githubusercontent.com/3306597/67027030-7f3acd00-f0ce-11e9-8b89-27acf898b04b.JPG).

New error:
2019-10-17 10:55:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/icloud3/device_tracker.py", line 1577, in _update_device_iosapp_trigger
    iosapp_version_text = 'ios' + self.iosapp_version.get(devicename)
TypeError: can only concatenate str (not "int") to str
2019-10-17 10:55:15 INFO (SyncWorker_3) [homeassistant.loader] Loaded nest from homeassistant.components.nest
2019-10-17 10:55:15 ERROR (SyncWorker_18) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_ios_trigger:OverallUpdate-can only concatenate str (not "int") to str)

**Comment by gcobb321** [comment]
At Chick-filet but managed to do an update on that last issue. Haven’t looked at previous one yet. YouCan Get the new version with the correction now. It was in a statement to show the version of the iOS app you are using.

Glad you found it.  I have started to change the docs to better explain how to get started and am going to add links to Apple site. Also changing find-my-phone name to FamilySharing since the locations for the devices on the 2fa account are really tied to the family sharing feature. Hopeful things will be clearer. Any thoughts?
