### ISSUE TITLE
No such file or directory: '/config/www/custom_cards/icloud3-event-log-card.js'

### ISSUE THREAD

**Issue by timota** [gcobb321/icloud3#73]
Hi, 
after upgrade to `v2.2.0-Release Candidate` got this error. 

```
2020-09-24 18:42:27 ERROR (SyncWorker_45) [custom_components.icloud3.device_tracker] [Errno 2] No such file or directory: '/config/www/custom_cards/icloud3-event-log-card.js'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 8105, in _check_ic3_event_log_file_version
    shutil.copy(ic3_evlog_filename, www_evlog_filename)
  File "/usr/local/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/config/www/custom_cards/icloud3-event-log-card.js'
2020-09-24 18:42:28 INFO (SyncWorker_45) [custom_components.icloud3.device_tracker]
```

**Comment by gcobb321** [comment]
Fixed in RC12b just uploaded
