### ISSUE TITLE
Another error: Data too long for column 'attributes' at row 1

### ISSUE THREAD

**Issue by timota** [gcobb321/icloud3#75]
v2.2.0-Release Candidate got this error.
```
2020-09-27 15:52:28 ERROR (Recorder) [homeassistant.components.recorder] Error saving events: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'attributes' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.icloud3_event_log', 'tarasiphone:Sun, 09/27, 15:52:27', '{"names": {"tarasiphone": "Taras"}, "log_level_debug": "", "filtername": "Taras", "update_time": "Sun, 09/27, 15:52:27", "logs": "[[\'15:52:25\', \'h ... (77838 characters truncated) ...  km\', \'Move into Stationary Zone Timer reached > tarasiphone, Expired-14:41:20\'], [\'00:00:00\', \'\', \'\', \'\', \'\', \'\', \'Last Record\']]"}', 16602809, datetime.datetime(2020, 9, 27, 14, 52, 27, 111384, tzinfo=<UTC>), datetime.datetime(2020, 9, 27, 14, 52, 27, 111384, tzinfo=<UTC>), datetime.datetime(2020, 9, 27, 14, 52, 27, 115950, tzinfo=<UTC>), 15910661)]
(Background on this error at: http://sqlalche.me/e/13/9h9h) (Background on this error at: http://sqlalche.me/e/13/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 435, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 486, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 502, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'attributes' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.icloud3_event_log', 'tarasiphone:Sun, 09/27, 15:52:27', '{"names": {"tarasiphone": "Taras"}, "log_level_debug": "", "filtername": "Taras", "update_time": "Sun, 09/27, 15:52:27", "logs": "[[\'15:52:25\', \'h ... (77838 characters truncated) ...  km\', \'Move into Stationary Zone Timer reached > tarasiphone, Expired-14:41:20\'], [\'00:00:00\', \'\', \'\', \'\', \'\', \'\', \'Last Record\']]"}', 16602809, datetime.datetime(2020, 9, 27, 14, 52, 27, 111384, tzinfo=<UTC>), datetime.datetime(2020, 9, 27, 14, 52, 27, 111384, tzinfo=<UTC>), datetime.datetime(2020, 9, 27, 14, 52, 27, 115950, tzinfo=<UTC>), 15910661)]
(Background on this error at: http://sqlalche.me/e/13/9h9h) (Background on this error at: http://sqlalche.me/e/13/7s2a)
```

**Comment by gcobb321** [comment]
Add an *exclude* option to the configuration.yaml file so it does not add *sensor.icloud3_event_log* to the HA history data base.

As an example, I am using the following to exclude all ipad sensors, all iOS App sensors and the Event Log sensor:
```
recorder:
  purge_keep_days: 5
  exclude:
    entity_globs:
      - sensor.*ipad*
      - sensor.*_app*
      - sensor.*_app2*
    entities:
      - sensor.icloud3_event_log
```

**Comment by timota** [comment]
Thanks for your help. It works. Error gone. 
As for me, it worth to add this to DOCs or FAQ. So any one with the same error will know how to fix it without opening an issue.

**Comment by gcobb321** [comment]
Glad it worked. It’s already in the new revamped docs for v2.2.0 on my system.
